[build.environment]
NODE_VERSION = "22"
DEBUG = "1"

[[redirects]]
  from = "/ph-events/*"
  to = "https://eu.i.posthog.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ph-static/*"
  to = "https://eu-assets.i.posthog.com/:splat"
  status = 200
  force = true