import { detect } from 'tinyld';

// ---------------------------------------------------------------------------
// Country → language keyword map
// Used for text-signal matching (requirement phrases, advantage phrases).
// ---------------------------------------------------------------------------

const COUNTRY_LANGUAGE_MAP: Record<string, string[]> = {
  FI: ['finnish', 'suomi', 'suomen'],
  SE: ['swedish', 'svenska'],
  NO: ['norwegian', 'norsk', 'bokmål', 'nynorsk'],
  DK: ['danish', 'dansk'],
  IS: ['icelandic', 'íslenska'],
  DE: ['german', 'deutsch'],
  AT: ['german', 'deutsch'],
  CH: ['german', 'deutsch', 'french', 'français', 'italian', 'italiano'],
  NL: ['dutch', 'nederlands'],
  BE: ['dutch', 'nederlands', 'french', 'français', 'flemish'],
  FR: ['french', 'français', 'francais'],
  IT: ['italian', 'italiano'],
  ES: ['spanish', 'español', 'espanol', 'castellano'],
  PT: ['portuguese', 'português', 'portugues'],
  PL: ['polish', 'polski'],
  CZ: ['czech', 'čeština', 'cestina'],
  SK: ['slovak', 'slovenčina'],
  HU: ['hungarian', 'magyar'],
  RO: ['romanian', 'română', 'romana'],
  BG: ['bulgarian', 'български'],
  HR: ['croatian', 'hrvatski'],
  SI: ['slovenian', 'slovenščina'],
  RS: ['serbian', 'srpski'],
  EE: ['estonian', 'eesti'],
  LV: ['latvian', 'latviešu'],
  LT: ['lithuanian', 'lietuvių'],
  GR: ['greek', 'ελληνικά'],
  TR: ['turkish', 'türkçe'],
  UA: ['ukrainian', 'українська'],
  RU: ['russian', 'русский'],
  GE: ['georgian', 'ქართული'],
  IL: ['hebrew', 'עברית'],
  JP: ['japanese', '日本語'],
  CN: ['chinese', 'mandarin', '普通话'],
  KR: ['korean', '한국어'],
  BA: ['bosnian', 'croatian', 'serbian'],
  MK: ['macedonian'],
  ME: ['montenegrin'],
  AL: ['albanian', 'shqip'],
  MD: ['romanian', 'moldovan'],
  BY: ['belarusian', 'russian'],
};

// Country → ISO 639-1 codes recognised by tinyld.
// Regional variants are listed explicitly (e.g. Norwegian: no / nb / nn).
const COUNTRY_LANG_CODES: Record<string, string[]> = {
  FI: ['fi'],
  SE: ['sv'],
  NO: ['no', 'nb', 'nn'],
  DK: ['da'],
  IS: ['is'],
  NL: ['nl'],
  DE: ['de'],
  AT: ['de'],
  CH: ['de', 'fr', 'it'],
  BE: ['nl', 'fr'],
  FR: ['fr'],
  IT: ['it'],
  ES: ['es'],
  PT: ['pt'],
  PL: ['pl'],
  CZ: ['cs'],
  SK: ['sk'],
  HU: ['hu'],
  RO: ['ro'],
  HR: ['hr'],
  SI: ['sl'],
  RS: ['sr'],
  EE: ['et'],
  LV: ['lv'],
  LT: ['lt'],
  BG: ['bg'],
  GR: ['el'],
  TR: ['tr'],
  UA: ['uk'],
  RU: ['ru'],
};

// Nordic/Scandinavian countries — used to gate group-language advantage phrases.
const NORDIC_COUNTRY_CODES = new Set(['FI', 'SE', 'NO', 'DK', 'IS']);

// Group-language advantage phrases: "a Nordic/Scandinavian language" is a regional
// umbrella term used in job ads to indicate that any Nordic language is a plus.
// These can't be generated by buildAdvantageSignals (which works per-language keyword)
// so they are listed statically here.
const NORDIC_LANGUAGE_REQUIREMENT_PHRASES = [
  'fluent in english and at least one nordic language',
  'fluent in english and at least one scandinavian language',
  'english and at least one nordic language',
  'english and at least one scandinavian language',
];

const NORDIC_LANGUAGE_ADVANTAGE_PHRASES = [
  'fluent in a nordic language',
  'fluent in a scandinavian language',
  'a nordic language is an advantage',
  'a nordic language is a plus',
  'a nordic language is a bonus',
  'a nordic language is preferred',
  'a nordic language is beneficial',
  'a nordic language would be an advantage',
  'a nordic language would be a plus',
  'a nordic language would be beneficial',
  'a nordic language seen as an advantage',
  'a scandinavian language is an advantage',
  'a scandinavian language is a plus',
  'a scandinavian language is a bonus',
  'a scandinavian language is preferred',
  'a scandinavian language would be an advantage',
  'a scandinavian language would be a plus',
  'knowledge of a nordic language',
  'knowledge of a scandinavian language',
  'nordic language skills is an advantage',
  'nordic language skills is a plus',
  'nordic language skills is preferred',
  'scandinavian language skills is an advantage',
  'scandinavian language skills is a plus',
];

// Phrases that explicitly confirm English is the working language.
const ENGLISH_ONLY_PHRASES = [
  'working language is english',
  'working language: english',
  'the working language is english',
  'company language is english',
  'our language is english',
  'english is our official language',
  'english is our company language',
  'english as the working language',
  'all communication in english',
  'english-speaking environment',
  'english speaking environment',
  'we work in english',
  'we communicate in english',
  'everything is in english',
  'english is the language',
  'english only environment',
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function stripHtml(html: string): string {
  // Convert block-level tags to newlines so paragraph structure survives for
  // tinyld chunk detection. Inline tags become spaces.
  return html
    .replace(/<\/?(p|div|li|h[1-6]|br|section|article|blockquote|tr)[^>]*>/gi, '\n')
    .replace(/<[^>]+>/g, ' ')
    .replace(/[ \t]+/g, ' ')
    .replace(/\n[ \t]*/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

/** True when the title contains non-ASCII characters typical of non-English languages. */
function titleAppearsNonEnglish(title: string): boolean {
  return /[äöüåéèêëàâîïôùûçñßãõøæœ]/i.test(title);
}

/**
 * Splits plain text into paragraphs and runs tinyld on each chunk that is
 * long enough to be reliable (≥80 chars). Returns true if any chunk is
 * detected as one of the target language codes.
 *
 * Paragraph-level detection handles mixed-language ads where e.g. the
 * introduction is in English but the requirements section is in German.
 */
function anyChunkInNativeLanguage(text: string, langCodes: string[]): boolean {
  if (!langCodes.length) return false;
  const chunks = text.split(/\n+/).map((c) => c.trim()).filter((c) => c.length >= 80);
  const candidates = chunks.length > 0 ? chunks : [text.trim()];
  for (const chunk of candidates) {
    if (langCodes.includes(detect(chunk))) return true;
  }
  return false;
}

/**
 * Builds compound "advantage" signal phrases for a given language keyword, e.g.:
 *   "finnish is an advantage", "knowledge of german would be beneficial"
 *
 * These indicate the language is preferred / nice-to-have, not required.
 */
function buildAdvantageSignals(lang: string): string[] {
  const langMentions = [
    lang,
    `${lang} skills`,
    `${lang} language`,
    `${lang} language skills`,
    `${lang} proficiency`,
    `proficiency in ${lang}`,
    `knowledge of ${lang}`,
    `${lang} knowledge`,
    `${lang} communication`,
    `preferably also ${lang}`,
  ];

  const advantageModifiers = [
    ' is an advantage',
    ' is a plus',
    ' is a big plus',
    ' is a bonus',
    ' is preferred',
    ' is desirable',
    ' is nice to have',
    ' is beneficial',
    ' would be an advantage',
    ' would be a plus',
    ' would be beneficial',
    ' would be an asset',
    ' is considered an advantage',
    ' is considered a plus',
    ' is considered a bonus',
    ' as a plus',
    ' as an advantage',
    ' seen as an advantage',
  ];

  const signals: string[] = [];
  for (const mention of langMentions) {
    for (const modifier of advantageModifiers) {
      signals.push(`${mention}${modifier}`);
    }
  }
  signals.push(`nice to have: ${lang}`);
  signals.push(`nice to have ${lang}`);
  return signals;
}

/** Explicit phrases that indicate the local language is required. */
function buildRequirementSignals(lang: string): string[] {
  return [
    // Direct requirement
    `${lang} required`,
    `${lang} is required`,
    `${lang} is a must`,
    `${lang} is mandatory`,
    `${lang} is essential`,
    `${lang} is necessary`,
    `${lang} is needed`,
    `${lang} is a requirement`,
    `${lang} fluency`,
    `requires ${lang}`,
    `must speak ${lang}`,
    `must be ${lang}`,
    // Fluency / proficiency
    `fluent ${lang}`,
    `fluent in ${lang}`,
    `fluency in ${lang}`,
    `proficiency in ${lang}`,
    `${lang} proficiency`,
    `proficient in ${lang}`,
    `working proficiency in ${lang}`,
    `${lang} language proficiency`,
    `working knowledge of ${lang}`,
    `knowledge of ${lang}`,
    // Level descriptors
    `business ${lang}`,
    `business-level ${lang}`,
    `professional ${lang}`,
    `${lang} at a professional level`,
    `${lang} at professional level`,
    // Native / mother tongue
    `native ${lang}`,
    `${lang} native`,
    `mother tongue ${lang}`,
    `${lang} as mother tongue`,
    `${lang} as a mother tongue`,
    `mother language ${lang}`,
    `${lang} as mother language`,
    `${lang} as a mother language`,
    // Speaker / communication
    `${lang} speaker`,
    `speaks ${lang}`,
    `speak ${lang}`,
    `communicate in ${lang}`,
    `${lang} communication skills`,
    `${lang} language skills`,
    `${lang} skills`,
    // Written + spoken
    `written and spoken ${lang}`,
    `spoken and written ${lang}`,
    `${lang} written and spoken`,
    `${lang} spoken and written`,
    // Working language phrasing
    `working language is ${lang}`,
    `working language: ${lang}`,
    `the working language is ${lang}`,
    `${lang} working language`,
    // "Both X and English" — local language is co-required alongside English
    `both ${lang} and`,
    `in both ${lang}`,
    `${lang} and english`,
    `english and ${lang}`,
    `${lang}/english`,
    `english/${lang}`,
  ];
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

export type NativeLanguageResult = {
  value: boolean;
  local_language_advantage: boolean;
};

/**
 * Determines whether a job requires (or advantages) knowledge of the local
 * language. Classification happens in two phases:
 *
 * **Phase 1 — Is the job ad itself in the native language?**
 * A non-English title or native-language description is a high-confidence
 * signal that the role requires native language skills.
 *
 * One subtlety: advantage-signal phrases are evaluated *before* running
 * tinyld. When `fetchPageHtml` is used the `descriptionHtml` may contain
 * a full HTML page — including native-language navigation, headers, and
 * footers — that would cause tinyld to fire even though the actual job
 * description says "Finnish is a plus". An explicit advantage phrase in the
 * combined text is a stronger, more specific signal and wins.
 *
 * **Phase 2 — English content analysis**
 * The description appears to be in English. Scan for explicit language
 * requirement or advantage phrases. If none are found, the absence of any
 * local language signal is itself strong evidence that English is sufficient.
 */
export function detectNativeLanguage(
  title: string,
  descriptionText: string | undefined,
  countryCode: string,
): NativeLanguageResult {
  const languages = COUNTRY_LANGUAGE_MAP[countryCode.toUpperCase()] ?? [];
  const langCodes = COUNTRY_LANG_CODES[countryCode.toUpperCase()] ?? [];

  // ── Phase 1a: Non-ASCII title ────────────────────────────────────────────
  // A job title with local-language characters is the clearest possible
  // signal — no further analysis needed.
  if (titleAppearsNonEnglish(title)) {
    return { value: true, local_language_advantage: false };
  }

  const descText = descriptionText ?? '';
  const combined = `${title} ${descText}`.toLowerCase();

  // ── Phase 1b: Advantage-signal pre-filter (before tinyld) ───────────────
  // Check for explicit "X is a plus / an advantage" phrases before running
  // tinyld. See the JSDoc above for why this ordering matters.
  for (const lang of languages) {
    for (const signal of buildAdvantageSignals(lang)) {
      if (combined.includes(signal)) {
        return { value: false, local_language_advantage: true };
      }
    }
  }

    // Group-language advantage phrases (e.g. "fluent in a Nordic language").
  if (NORDIC_COUNTRY_CODES.has(countryCode.toUpperCase())) {
    for (const phrase of NORDIC_LANGUAGE_ADVANTAGE_PHRASES) {
      if (combined.includes(phrase)) {
        return { value: false, local_language_advantage: true };
      }
    }
  }

  // ── Phase 1c: tinyld content language detection ──────────────────────────
  // If any paragraph of the description is detected as the country's
  // language, the ad is (at least partially) written in that language.
  if (anyChunkInNativeLanguage(descText, langCodes)) {
    return { value: true, local_language_advantage: false };
  }

  // ── Phase 2a: Explicit language requirement signals ──────────────────────
  // The description is in English — scan for phrases that explicitly require
  // the local language (e.g. "fluent Finnish", "working language is German").
  if (NORDIC_COUNTRY_CODES.has(countryCode.toUpperCase())) {
    for (const phrase of NORDIC_LANGUAGE_REQUIREMENT_PHRASES) {
      if (combined.includes(phrase)) {
        return { value: true, local_language_advantage: false };
      }
    }
  }

  for (const lang of languages) {
    for (const signal of buildRequirementSignals(lang)) {
      if (combined.includes(signal)) {
        return { value: true, local_language_advantage: false };
      }
    }
  }

  // ── Phase 2b: "depending on location" conditional requirement ───────────
  // e.g. "Fluent English and, depending on the location, Finnish, Swedish or Lithuanian."
  // The country's language may not be the first listed, so we can't rely on
  // substring order — we check for the trigger phrase + language anywhere in the text.
  if (/depending on (?:the |your )?location/i.test(combined)) {
    for (const lang of languages) {
      if (combined.includes(lang)) {
        return { value: true, local_language_advantage: false };
      }
    }
  }

  // ── Phase 2c: Explicit English-only confirmation ─────────────────────────
  for (const phrase of ENGLISH_ONLY_PHRASES) {
    if (combined.includes(phrase)) {
      return { value: false, local_language_advantage: false };
    }
  }

  // ── Phase 2d default ─────────────────────────────────────────────────────
  // No explicit signals found — absence of any local language requirement is
  // itself a strong signal that English is sufficient.
  return { value: false, local_language_advantage: false };
}
