/**
 * Test fixtures for the language classifier (detectNativeLanguage).
 *
 * One entry per signal pattern. When you add a new pattern to the classifier
 * (a phrase, a negation rule, a Nordic group phrase, etc.) add a matching
 * entry here so regressions are caught automatically.
 *
 * Phases mirror the detectNativeLanguage() implementation:
 *   1a        — non-ASCII or keyword in title
 *   1b        — explicit advantage phrase (before tinyld)
 *   1b-chars  — native character count in description
 *   1c        — tinyld detects country language (not tested here — ML-model-dependent)
 *   2a        — explicit requirement phrase in English description
 *   2a-nordic — group Nordic/Scandinavian requirement phrase
 *   2a-cross  — cross-language requirement / advantage
 *   2b        — "depending on location" conditional requirement
 *   2d        — no signal → English assumed
 */

export type FixtureCase = {
    label: string;
    title: string;
    desc?: string;
    country: string;
    requires: boolean;
    advantage: boolean;
};

// Long native-language descriptions used for Phase 1b-chars tests.
// Each must exceed the COUNTRY_NATIVE_CHARS threshold for its language.
// Finnish / Swedish: 15+ ä/ö chars; German: 10+ ä/ö/ü/ß; Norwegian: 15+ æ/ø/å.
const FINNISH_NATIVE_DESC =
    'Etsimme ohjelmistokehittäjää tiimimme vahvistukseksi. Työnkuvan keskeisiä tehtäviä ovat ' +
    'järjestelmäkehitys, tietokantojen ylläpitäminen ja uusien ratkaisujen kehittäminen. ' +
    'Odotamme hakijalta hyvää kykyä kommunikoida sekä taitoa käyttää moderneja ' +
    'kehitystyökaluja. Tärkeää on myös kyky priorisoida tehtäviä ja työskennellä joustavasti.';

const GERMAN_NATIVE_DESC =
    'Wir suchen einen erfahrenen Softwareentwickler für unser wachsendes Münchener Team. ' +
    'Sie übernehmen Verantwortung für Entwicklung und können Ihre Fähigkeiten täglich ' +
    'unter Beweis stellen. Außerdem bieten wir außergewöhnliche Möglichkeiten, Ihre ' +
    'persönlichen und fachlichen Stärken weiterzuentwickeln. Die Lösung komplexer ' +
    'Aufgaben gehört zu Ihren täglichen Tätigkeiten.';

const NORWEGIAN_NATIVE_DESC =
    'Vi søker en engasjert og dyktig programvareutvikler som ønsker å jobbe med spennende ' +
    'faglige utfordringer. Stillingen innebærer å ta ansvar for utvikling og vedlikehold ' +
    'av systemer og løsninger. Du bør ha god kunnskap om fagområdet og evne til å ' +
    'samarbeide på tvers av avdelinger. Hos oss får du muligheten til å vokse faglig, ' +
    'og vi tilbyr gode muligheter for utvikling i et dynamisk og fagsterkt miljø.';

export const CASES: FixtureCase[] = [
    // ── Phase 1a: Non-ASCII or keyword in title ──────────────────────────────

    // ── Phase 1a: Non-ASCII or keyword in title ──────────────────────────────

    {
        label: '1a — German title with ä/ü chars',
        title: 'Softwareentwickler (m/w/d) für München',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '1a — Finnish title with ä char',
        title: 'Ohjelmistokehittäjä',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '1a — Norwegian title with å char',
        title: 'Rådgiver – teknologi',
        country: 'NO',
        requires: true,
        advantage: false,
    },
    {
        label: '1a — Swedish keyword "säljare" in title',
        title: 'Säljare B2B',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '1a — Finnish keyword "myynti" in title',
        title: 'Myynti Specialist',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '1a — German keyword "entwickler" in title',
        title: 'Senior Entwickler Backend',
        country: 'DE',
        requires: true,
        advantage: false,
    },

    // ── Phase 1b: Advantage pre-filter (short English desc, no tinyld) ───────
    // These phrases fire before tinyld so they work on short descriptions too.

    {
        label: '1b — "Finnish is a plus"',
        title: 'Software Engineer',
        desc: 'You will work with our international team. Finnish is a plus.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish is an advantage"',
        title: 'Software Engineer',
        desc: 'Excellent communication skills required. Finnish is an advantage.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish is a strong advantage"',
        title: 'Account Manager',
        desc: 'Experience in B2B sales required. Finnish is a strong advantage.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish language skills is a bonus"',
        title: 'Sales Specialist',
        desc: 'Strong English required. Finnish language skills is a bonus.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish is preferred"',
        title: 'Customer Success Manager',
        desc: 'Strong English is required. Finnish is preferred.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "proficiency in Norwegian is preferred" cross-language advantage on FI job',
        title: 'Project Manager',
        desc: 'Strong English is required. Proficiency in Norwegian is preferred.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish is desirable"',
        title: 'Business Analyst',
        desc: 'Finnish is desirable but not required.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish is nice to have"',
        title: 'UX Designer',
        desc: 'Portfolio required. Finnish is nice to have.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish would be beneficial"',
        title: 'Project Manager',
        desc: 'PMP certification preferred. Finnish would be beneficial.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "nice to have: Finnish"',
        title: 'Data Engineer',
        desc: 'Requirements: Python, SQL. Nice to have: Finnish.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "preferably Finnish"',
        title: 'Operations Coordinator',
        desc: 'We work in English. Preferably Finnish.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish preferred"',
        title: 'Customer Support Specialist',
        desc: 'English required. Finnish preferred.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "knowledge of Finnish is an advantage"',
        title: 'Marketing Manager',
        desc: 'Experience in digital marketing. Knowledge of Finnish is an advantage.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish language skills would be a plus"',
        title: 'Sales Engineer',
        desc: 'Technical background required. Finnish language skills would be a plus.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish is considered an additional qualification"',
        title: 'HR Business Partner',
        desc: 'HR experience required. Finnish is considered an additional qualification.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Swedish skills is a plus" (Swedish country)',
        title: 'Software Developer',
        desc: 'Join our team. Swedish skills is a plus.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "German is an advantage"',
        title: 'Backend Developer',
        desc: 'Strong Python skills. German is an advantage.',
        country: 'DE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Dutch language skills are a plus" (Netherlands)',
        title: 'Product Manager',
        desc: 'Road-mapping experience needed. Dutch language skills are a plus.',
        country: 'NL',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Swedish is highly valuable for many local client engagements" → advantage',
        title: 'Account Manager',
        desc: 'Swedish is highly valuable for many local client engagements.',
        country: 'SE',
        requires: false,
        advantage: true,
    },

    // ── Phase 1b: Nordic/Scandinavian group advantage phrases ─────────────────

    {
        label: '1b — "a Nordic language is an advantage"',
        title: 'Key Account Manager',
        desc: 'Working language is English. A Nordic language is an advantage.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "a Scandinavian language is a plus"',
        title: 'Sales Director',
        desc: 'Travel required. A Scandinavian language is a plus.',
        country: 'NO',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "knowledge of a Nordic language"',
        title: 'Finance Analyst',
        desc: 'CPA preferred. Knowledge of a Nordic language.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Nordic language skills is a plus"',
        title: 'Regional Manager',
        desc: 'Management experience required. Nordic language skills is a plus.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "ideally including Norwegian" parenthetical advantage phrase',
        title: 'Customer Success Manager',
        desc: 'Nordic language skills (ideally including Norwegian) are important to achieve the needed customer and work content intimacy.',
        country: 'NO',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "a Nordic language would be a plus"',
        title: 'Business Development Manager',
        desc: 'B2B sales background. A Nordic language would be a plus.',
        country: 'DK',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "a Nordic language is a strong advantage"',
        title: 'Customer Success Lead',
        desc: 'Strong client management skills. A Nordic language is a strong advantage.',
        country: 'NO',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "nordic languages are a plus but not a requirement"',
        title: 'Solutions Architect',
        desc: 'Cloud expertise required. Nordic languages are a plus but not a requirement.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — regex: "Swedish or other Nordic languages are a plus"',
        title: 'Regional Sales Manager',
        desc: 'English fluency required. Swedish or other Nordic languages are a plus.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — regex: "Knowledge of Nordic or Baltic languages is an advantage"',
        title: 'Market Analyst',
        desc: 'Analytical skills required. Knowledge of Nordic or Baltic languages is an advantage.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — regex: "Finnish or other Nordic languages are a plus"',
        title: 'Account Executive',
        desc: 'Sales experience required. Finnish or other Nordic languages are a plus.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — regex: "knowledge of Scandinavian languages is an asset"',
        title: 'Communications Manager',
        desc: 'Media background preferred. Knowledge of Scandinavian languages is an asset.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "proficiency in a Nordic language is preferred" → advantage (substring match)',
        title: 'Solutions Consultant',
        desc: 'Fluency in English; proficiency in a Nordic language is preferred.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "(Fluency in another Nordic language is a plus.)" → advantage',
        title: 'Support Specialist',
        desc: 'Fluency in English. (Fluency in another Nordic language is a plus.)',
        country: 'NO',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Nordic language skills are a plus" (plural "are") → advantage',
        title: 'Support Specialist',
        desc: 'Fluent English required; Nordic language skills are a plus.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '2a — requirement in one clause not negated by advantage phrase in a later clause',
        title: 'Account Manager',
        desc: 'Fluent in English and Norwegian; Danish or Finnish considered as an advantage',
        country: 'NO',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Fluent in English and Norwegian" (no trailing advantage clause) → required',
        title: 'Account Manager',
        desc: 'Fluent in English and Norwegian.',
        country: 'NO',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — requirement not negated by advantage phrase in a later paragraph (newline-separated, no punctuation)',
        title: 'Account Manager',
        desc: 'Fluent in English and Norwegian\n\nDanish or Finnish considered as an advantage',
        country: 'NO',
        requires: true,
        advantage: false,
    },

    // ── Phase 1b: Requirement wins when both signals are present ─────────────

    {
        label: '1b override — requirement wins over co-present advantage phrase',
        title: 'Customer Manager',
        desc: 'Fluent Finnish is required for this role. Finnish is a plus for career growth.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a negation-advantage — "proficiency in Norwegian is preferred" → advantage',
        title: 'Project Manager',
        desc: 'Proficiency in Norwegian is preferred for this Nordic-focused role.',
        country: 'NO',
        requires: false,
        advantage: true,
    },
    {
        label: '2a negation-advantage — "Norwegian language skills is a bonus" → advantage',
        title: 'Sales Director',
        desc: 'Norwegian language skills is a bonus in our Oslo office.',
        country: 'NO',
        requires: false,
        advantage: true,
    },
    {
        label: '2a negation-advantage — "fluent Finnish is a plus" → advantage (not requirement wins)',
        title: 'Support Engineer',
        desc: 'Fluent Finnish is a plus for working with Finnish clients.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '2a — "Fluent Finnish required. Swedish is preferred." — Finnish still required',
        title: 'Nordic Manager',
        desc: 'Fluent Finnish required. Swedish is preferred for the Nordic team.',
        country: 'FI',
        requires: true,
        advantage: false,
    },

    // ── Phase 1b-chars: Native character frequency ────────────────────────────
    // Full native-language paragraphs that exceed the per-country threshold.

    {
        label: '1b-chars — Finnish description with 15+ ä/ö chars',
        title: 'Software Developer',
        desc: FINNISH_NATIVE_DESC,
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '1b-chars — German description with 10+ ä/ö/ü/ß chars',
        title: 'Software Engineer',
        desc: GERMAN_NATIVE_DESC,
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '1b-chars — Norwegian description with 15+ æ/ø/å chars',
        title: 'Developer',
        desc: NORWEGIAN_NATIVE_DESC,
        country: 'NO',
        requires: true,
        advantage: false,
    },

    // ── Phase 2a: Explicit requirement phrases ────────────────────────────────
    // Short English descriptions — tinyld and char-check won't fire.

    {
        label: '2a — "Finnish required"',
        title: 'Customer Support Specialist',
        desc: 'Finnish required. English also needed.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish is required"',
        title: 'Service Advisor',
        desc: 'Finnish is required for daily client communication.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "fluent in Finnish"',
        title: 'Sales Manager',
        desc: 'You must be fluent in Finnish and English.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "fluent Finnish"',
        title: 'Account Manager',
        desc: 'Fluent Finnish is essential for this client-facing role.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "fluent in spoken Finnish"',
        title: 'Customer Support Specialist',
        desc: 'Fluent in spoken Finnish and the ability to produce clear and professional content in Finnish.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish is a must"',
        title: 'Support Engineer',
        desc: 'Finnish is a must; English is also required.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish is mandatory"',
        title: 'Field Technician',
        desc: 'Finnish is mandatory for client interactions.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish fluency"',
        title: 'Client Success Manager',
        desc: 'Requirements: Finnish fluency, English proficiency.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "fluency in Finnish"',
        title: 'Sales Consultant',
        desc: 'Fluency in Finnish required for this customer-facing role.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "proficient in Finnish"',
        title: 'Analyst',
        desc: 'You should be proficient in Finnish and English.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "native Finnish"',
        title: 'Content Writer',
        desc: 'Native Finnish required for copy editing.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish speaker"',
        title: 'Customer Advisor',
        desc: 'We are looking for a Finnish speaker to join our team.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "written and spoken Finnish"',
        title: 'HR Coordinator',
        desc: 'Excellent written and spoken Finnish required.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "working language is Finnish"',
        title: 'Team Lead',
        desc: 'The working language is Finnish within the team.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish and English"',
        title: 'Office Manager',
        desc: 'You must communicate in Finnish and English daily.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "English and Finnish"',
        title: 'Project Coordinator',
        desc: 'Strong skills in English and Finnish are required.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish, English" comma list',
        title: 'Support Specialist',
        desc: 'Language requirements: Finnish, English.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "knowledge of Finnish"',
        title: 'Business Consultant',
        desc: 'Knowledge of Finnish is required for the role.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish language skills"',
        title: 'Relationship Manager',
        desc: 'Finnish language skills are essential.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish skills"',
        title: 'Communication Specialist',
        desc: 'Finnish skills required for daily operations.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "basic Finnish"',
        title: 'Field Operative',
        desc: 'Basic Finnish needed to communicate with local colleagues.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish/English" slash notation',
        title: 'Technical Support',
        desc: 'Finnish/English speaking environment.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Norwegian/Swedish/Danish speaking" slash expansion',
        title: 'Nordic Sales Manager',
        desc: 'Norwegian/Swedish/Danish speaking candidates preferred.',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "German required"',
        title: 'Client Manager',
        desc: 'German required for all internal and client communications.',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Dutch language skills" (Netherlands)',
        title: 'Operations Manager',
        desc: 'Dutch language skills are required for this position.',
        country: 'NL',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "communicate confidently in Finnish"',
        title: 'Sales Representative',
        desc: 'You must be able to communicate confidently in Finnish.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "understand Swedish and English fluently" — understanding both is required',
        title: 'Operations Manager',
        desc: 'You understand Swedish and English fluently and can speak either Swedish or English proficiently.',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "both swedish and" — "Full working proficiency in both Swedish and English"',
        title: 'Business Analyst',
        desc: 'Full working proficiency in both Swedish and English.',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "both swedish and" — "fluency in both Swedish and English is required"',
        title: 'Operations Lead',
        desc: 'fluency in both Swedish and English is required, spoken and written.',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "excellent swedish" — co-requirement with English',
        title: 'Client Relations Manager',
        desc: 'Excellent Swedish and English language skills and Swedish work permit required.',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "finnish and english" — "presentations skills in Finnish and English"',
        title: 'Communications Specialist',
        desc: 'Fluent communication and presentations skills in Finnish and English.',
        country: 'FI',
        requires: true,
        advantage: false,
    },

    // ── Phase 2a: Mixed English + local language requirement phrases ──────────
    {
        label: '2a — "Fluent English (written and spoken), elementary German"',
        title: 'Consultant',
        desc: 'Fluent English (written and spoken), elementary German',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "fluent in English ... good in German"',
        title: 'Consultant',
        desc: 'Language skills: fluent in English (written and verbal), good in German (written and verbal)',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "German (C1 level) and English"',
        title: 'Consultant',
        desc: 'German (C1 level) and English',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — CEFR level before language: "at least a B2 level of German"',
        title: 'Stakeholder Manager',
        desc: 'You are fluent in English (C1/C2) and possess at least a B2 level of German to navigate local stakeholder and city relationships.',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Native in German" with English co-requirement',
        title: 'Consultant',
        desc: 'Excellent communication and presentation skills in English. Native in German.',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Fluency in English + Swedish"',
        title: 'Consultant',
        desc: 'Fluency in English + Swedish',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "English and local language Swedish or Danish or Finnish"',
        title: 'Consultant',
        desc: 'Fluent in both English and local language Swedish or Danish or Finnish',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "fluent in local language and English"',
        title: 'Consultant',
        desc: 'You are fluent in local language and English, and are able to make our customers feel listened to.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Business level English / Local language: Fluent"',
        title: 'Consultant',
        desc: 'Business level English: Fluent\nLocal language: Fluent, Business Level',
        country: 'FI',
        requires: true,
        advantage: false,
    },

    // ── Phase 2a: Explicit advantage phrases ──────────────────────────────────

    {
        label: '2a advantage — "Arabic a plus"',
        title: 'Consultant',
        desc: 'English language skills. Arabic a plus',
        country: 'DE',
        requires: false,
        advantage: true,
    },
    {
        label: '2a advantage — "local language is a plus"',
        title: 'Consultant',
        desc: 'Multi-lingual: Proficient in English. One of the most spoken EMEA local language is a plus i.e. French, Italian, Spanish, Dutch, Arabic.',
        country: 'NL',
        requires: false,
        advantage: true,
    },
    //{
    //  label: '2a advantage — "Dutch ... preferred"',
    //  title: 'Consultant',
    //  desc: 'High level of English (written and oral) is required, Dutch speaking skills on top of that are preferred.',
    //  country: 'NL',
    //  requires: false,
    //  advantage: true,
    //},
    {
        label: '2a advantage — "Dutch ... added value"',
        title: 'Consultant',
        desc: 'Additional fluent language skills in the local language Dutch are of great added value.',
        country: 'NL',
        requires: false,
        advantage: true,
    },
    {
        label: '2a advantage — "additional Dutch is considered a plus"',
        title: 'Consultant',
        desc: 'Fluency in English (additional Dutch is considered a plus).',
        country: 'NL',
        requires: false,
        advantage: true,
    },
    {
        label: '2a advantage — "Dutch is preferable"',
        title: 'Consultant',
        desc: 'Language: fluent English and Dutch is preferable',
        country: 'NL',
        requires: false,
        advantage: true,
    },

    // ── Phase 2a: "knowledge of X" adjective guard ────────────────────────────

    {
        label: '2a adjective — "knowledge of Dutch law" not a language signal',
        title: 'Legal Counsel',
        desc: 'Knowledge of Dutch law and corporate regulations is required.',
        country: 'NL',
        requires: false,
        advantage: false,
    },
    {
        label: '2a adjective — "knowledge of German market" not a language signal',
        title: 'Sales Director',
        desc: 'Knowledge of German market dynamics is essential.',
        country: 'DE',
        requires: false,
        advantage: false,
    },
    {
        label: '2a adjective — "knowledge of Dutch" alone IS a language signal',
        title: 'Support Engineer',
        desc: 'Knowledge of Dutch required for client calls.',
        country: 'NL',
        requires: true,
        advantage: false,
    },

    // ── Phase 2a: Negation — "or English" downgrades to no signal ─────────────

    {
        label: '2a negation-none — "fluent in Finnish or English" → no signal',
        title: 'Engineer',
        desc: 'You should be fluent in Finnish or English.',
        country: 'FI',
        requires: false,
        advantage: false,
    },
    {
        label: '2a negation-none — "Finnish fluency or English" → no signal',
        title: 'Analyst',
        desc: 'Finnish fluency or English accepted.',
        country: 'FI',
        requires: false,
        advantage: false,
    },
    {
        label: '1a — German title with ä/ü chars',
        title: 'Softwareentwickler (m/w/d) für München',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '1a — Finnish title with ä char',
        title: 'Ohjelmistokehittäjä',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '1a — Norwegian title with å char',
        title: 'Rådgiver – teknologi',
        country: 'NO',
        requires: true,
        advantage: false,
    },
    {
        label: '1a — Swedish keyword "säljare" in title',
        title: 'Säljare B2B',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '1a — Finnish keyword "myynti" in title',
        title: 'Myynti Specialist',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '1a — German keyword "entwickler" in title',
        title: 'Senior Entwickler Backend',
        country: 'DE',
        requires: true,
        advantage: false,
    },

    // ── Phase 1b: Advantage pre-filter (short English desc, no tinyld) ───────
    // These phrases fire before tinyld so they work on short descriptions too.

    {
        label: '1b — "Finnish is a plus"',
        title: 'Software Engineer',
        desc: 'You will work with our international team. Finnish is a plus.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish is an advantage"',
        title: 'Software Engineer',
        desc: 'Excellent communication skills required. Finnish is an advantage.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish is a strong advantage"',
        title: 'Account Manager',
        desc: 'Experience in B2B sales required. Finnish is a strong advantage.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish language skills is a bonus"',
        title: 'Sales Specialist',
        desc: 'Strong English required. Finnish language skills is a bonus.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish is preferred"',
        title: 'Customer Success Manager',
        desc: 'Strong English is required. Finnish is preferred.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "proficiency in Norwegian is preferred" cross-language advantage on FI job',
        title: 'Project Manager',
        desc: 'Strong English is required. Proficiency in Norwegian is preferred.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish is desirable"',
        title: 'Business Analyst',
        desc: 'Finnish is desirable but not required.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish is nice to have"',
        title: 'UX Designer',
        desc: 'Portfolio required. Finnish is nice to have.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish would be beneficial"',
        title: 'Project Manager',
        desc: 'PMP certification preferred. Finnish would be beneficial.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "nice to have: Finnish"',
        title: 'Data Engineer',
        desc: 'Requirements: Python, SQL. Nice to have: Finnish.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "preferably Finnish"',
        title: 'Operations Coordinator',
        desc: 'We work in English. Preferably Finnish.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish preferred"',
        title: 'Customer Support Specialist',
        desc: 'English required. Finnish preferred.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "knowledge of Finnish is an advantage"',
        title: 'Marketing Manager',
        desc: 'Experience in digital marketing. Knowledge of Finnish is an advantage.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish language skills would be a plus"',
        title: 'Sales Engineer',
        desc: 'Technical background required. Finnish language skills would be a plus.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Finnish is considered an additional qualification"',
        title: 'HR Business Partner',
        desc: 'HR experience required. Finnish is considered an additional qualification.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Swedish skills is a plus" (Swedish country)',
        title: 'Software Developer',
        desc: 'Join our team. Swedish skills is a plus.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "German is an advantage"',
        title: 'Backend Developer',
        desc: 'Strong Python skills. German is an advantage.',
        country: 'DE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Dutch language skills are a plus" (Netherlands)',
        title: 'Product Manager',
        desc: 'Road-mapping experience needed. Dutch language skills are a plus.',
        country: 'NL',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Swedish is highly valuable for many local client engagements" → advantage',
        title: 'Account Manager',
        desc: 'Swedish is highly valuable for many local client engagements.',
        country: 'SE',
        requires: false,
        advantage: true,
    },

    // ── Phase 1b: Nordic/Scandinavian group advantage phrases ─────────────────

    {
        label: '1b — "a Nordic language is an advantage"',
        title: 'Key Account Manager',
        desc: 'Working language is English. A Nordic language is an advantage.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "a Scandinavian language is a plus"',
        title: 'Sales Director',
        desc: 'Travel required. A Scandinavian language is a plus.',
        country: 'NO',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "knowledge of a Nordic language"',
        title: 'Finance Analyst',
        desc: 'CPA preferred. Knowledge of a Nordic language.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Nordic language skills is a plus"',
        title: 'Regional Manager',
        desc: 'Management experience required. Nordic language skills is a plus.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "a Nordic language would be a plus"',
        title: 'Business Development Manager',
        desc: 'B2B sales background. A Nordic language would be a plus.',
        country: 'DK',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "a Nordic language is a strong advantage"',
        title: 'Customer Success Lead',
        desc: 'Strong client management skills. A Nordic language is a strong advantage.',
        country: 'NO',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "nordic languages are a plus but not a requirement"',
        title: 'Solutions Architect',
        desc: 'Cloud expertise required. Nordic languages are a plus but not a requirement.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — regex: "Swedish or other Nordic languages are a plus"',
        title: 'Regional Sales Manager',
        desc: 'English fluency required. Swedish or other Nordic languages are a plus.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — regex: "Knowledge of Nordic or Baltic languages is an advantage"',
        title: 'Market Analyst',
        desc: 'Analytical skills required. Knowledge of Nordic or Baltic languages is an advantage.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — regex: "Finnish or other Nordic languages are a plus"',
        title: 'Account Executive',
        desc: 'Sales experience required. Finnish or other Nordic languages are a plus.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — regex: "knowledge of Scandinavian languages is an asset"',
        title: 'Communications Manager',
        desc: 'Media background preferred. Knowledge of Scandinavian languages is an asset.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "proficiency in a Nordic language is preferred" → advantage (substring match)',
        title: 'Solutions Consultant',
        desc: 'Fluency in English; proficiency in a Nordic language is preferred.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "(Fluency in another Nordic language is a plus.)" → advantage',
        title: 'Support Specialist',
        desc: 'Fluency in English. (Fluency in another Nordic language is a plus.)',
        country: 'NO',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Nordic language skills are a plus" (plural "are") → advantage',
        title: 'Support Specialist',
        desc: 'Fluent English required; Nordic language skills are a plus.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '2a — requirement in one clause not negated by advantage phrase in a later clause',
        title: 'Account Manager',
        desc: 'Fluent in English and Norwegian; Danish or Finnish considered as an advantage',
        country: 'NO',
        requires: true,
        advantage: false,
    },

    // ── Phase 1b: Requirement wins when both signals are present ─────────────

    {
        label: '1b override — requirement wins over co-present advantage phrase',
        title: 'Customer Manager',
        desc: 'Fluent Finnish is required for this role. Finnish is a plus for career growth.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a negation-advantage — "proficiency in Norwegian is preferred" → advantage',
        title: 'Project Manager',
        desc: 'Proficiency in Norwegian is preferred for this Nordic-focused role.',
        country: 'NO',
        requires: false,
        advantage: true,
    },
    {
        label: '2a negation-advantage — "Norwegian language skills is a bonus" → advantage',
        title: 'Sales Director',
        desc: 'Norwegian language skills is a bonus in our Oslo office.',
        country: 'NO',
        requires: false,
        advantage: true,
    },
    {
        label: '2a negation-advantage — "fluent Finnish is a plus" → advantage (not requirement wins)',
        title: 'Support Engineer',
        desc: 'Fluent Finnish is a plus for working with Finnish clients.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '2a — "Fluent Finnish required. Swedish is preferred." — Finnish still required',
        title: 'Nordic Manager',
        desc: 'Fluent Finnish required. Swedish is preferred for the Nordic team.',
        country: 'FI',
        requires: true,
        advantage: false,
    },

    // ── Phase 1b-chars: Native character frequency ────────────────────────────
    // Full native-language paragraphs that exceed the per-country threshold.

    {
        label: '1b-chars — Finnish description with 15+ ä/ö chars',
        title: 'Software Developer',
        desc: FINNISH_NATIVE_DESC,
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '1b-chars — German description with 10+ ä/ö/ü/ß chars',
        title: 'Software Engineer',
        desc: GERMAN_NATIVE_DESC,
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '1b-chars — Norwegian description with 15+ æ/ø/å chars',
        title: 'Developer',
        desc: NORWEGIAN_NATIVE_DESC,
        country: 'NO',
        requires: true,
        advantage: false,
    },

    // ── Phase 2a: Explicit requirement phrases ────────────────────────────────
    // Short English descriptions — tinyld and char-check won't fire.

    {
        label: '2a — "Finnish required"',
        title: 'Customer Support Specialist',
        desc: 'Finnish required. English also needed.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish is required"',
        title: 'Service Advisor',
        desc: 'Finnish is required for daily client communication.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "fluent in Finnish"',
        title: 'Sales Manager',
        desc: 'You must be fluent in Finnish and English.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "fluent Finnish"',
        title: 'Account Manager',
        desc: 'Fluent Finnish is essential for this client-facing role.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish is a must"',
        title: 'Support Engineer',
        desc: 'Finnish is a must; English is also required.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish is mandatory"',
        title: 'Field Technician',
        desc: 'Finnish is mandatory for client interactions.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish fluency"',
        title: 'Client Success Manager',
        desc: 'Requirements: Finnish fluency, English proficiency.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "fluency in Finnish"',
        title: 'Sales Consultant',
        desc: 'Fluency in Finnish required for this customer-facing role.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "proficient in Finnish"',
        title: 'Analyst',
        desc: 'You should be proficient in Finnish and English.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "native Finnish"',
        title: 'Content Writer',
        desc: 'Native Finnish required for copy editing.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish speaker"',
        title: 'Customer Advisor',
        desc: 'We are looking for a Finnish speaker to join our team.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "written and spoken Finnish"',
        title: 'HR Coordinator',
        desc: 'Excellent written and spoken Finnish required.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "working language is Finnish"',
        title: 'Team Lead',
        desc: 'The working language is Finnish within the team.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish and English"',
        title: 'Office Manager',
        desc: 'You must communicate in Finnish and English daily.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "English and Finnish"',
        title: 'Project Coordinator',
        desc: 'Strong skills in English and Finnish are required.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish, English" comma list',
        title: 'Support Specialist',
        desc: 'Language requirements: Finnish, English.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "knowledge of Finnish"',
        title: 'Business Consultant',
        desc: 'Knowledge of Finnish is required for the role.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish language skills"',
        title: 'Relationship Manager',
        desc: 'Finnish language skills are essential.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish skills"',
        title: 'Communication Specialist',
        desc: 'Finnish skills required for daily operations.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "basic Finnish"',
        title: 'Field Operative',
        desc: 'Basic Finnish needed to communicate with local colleagues.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Finnish/English" slash notation',
        title: 'Technical Support',
        desc: 'Finnish/English speaking environment.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Norwegian/Swedish/Danish speaking" slash expansion',
        title: 'Nordic Sales Manager',
        desc: 'Norwegian/Swedish/Danish speaking candidates preferred.',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "German required"',
        title: 'Client Manager',
        desc: 'German required for all internal and client communications.',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Dutch language skills" (Netherlands)',
        title: 'Operations Manager',
        desc: 'Dutch language skills are required for this position.',
        country: 'NL',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "communicate confidently in Finnish"',
        title: 'Sales Representative',
        desc: 'You must be able to communicate confidently in Finnish.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "understand Swedish and English fluently" — understanding both is required',
        title: 'Operations Manager',
        desc: 'You understand Swedish and English fluently and can speak either Swedish or English proficiently.',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "both swedish and" — "Full working proficiency in both Swedish and English"',
        title: 'Business Analyst',
        desc: 'Full working proficiency in both Swedish and English.',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "both swedish and" — "fluency in both Swedish and English is required"',
        title: 'Operations Lead',
        desc: 'fluency in both Swedish and English is required, spoken and written.',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "excellent swedish" — co-requirement with English',
        title: 'Client Relations Manager',
        desc: 'Excellent Swedish and English language skills and Swedish work permit required.',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "finnish and english" — "presentations skills in Finnish and English"',
        title: 'Communications Specialist',
        desc: 'Fluent communication and presentations skills in Finnish and English.',
        country: 'FI',
        requires: true,
        advantage: false,
    },

    // ── Phase 2a: Mixed English + local language requirement phrases ──────────
    {
        label: '2a — "Fluent English (written and spoken), elementary German"',
        title: 'Consultant',
        desc: 'Fluent English (written and spoken), elementary German',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "fluent in English ... good in German"',
        title: 'Consultant',
        desc: 'Language skills: fluent in English (written and verbal), good in German (written and verbal)',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "German (C1 level) and English"',
        title: 'Consultant',
        desc: 'German (C1 level) and English',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — CEFR level before language: "at least a B2 level of German"',
        title: 'Stakeholder Manager',
        desc: 'You are fluent in English (C1/C2) and possess at least a B2 level of German to navigate local stakeholder and city relationships.',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Native in German" with English co-requirement',
        title: 'Consultant',
        desc: 'Excellent communication and presentation skills in English. Native in German.',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Fluency in English + Swedish"',
        title: 'Consultant',
        desc: 'Fluency in English + Swedish',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "English and local language Swedish or Danish or Finnish"',
        title: 'Consultant',
        desc: 'Fluent in both English and local language Swedish or Danish or Finnish',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "fluent in local language and English"',
        title: 'Consultant',
        desc: 'You are fluent in local language and English, and are able to make our customers feel listened to.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Business level English / Local language: Fluent"',
        title: 'Consultant',
        desc: 'Business level English: Fluent\nLocal language: Fluent, Business Level',
        country: 'FI',
        requires: true,
        advantage: false,
    },

    // ── Phase 2a: Explicit advantage phrases ──────────────────────────────────

    {
        label: '2a advantage — "Arabic a plus"',
        title: 'Consultant',
        desc: 'English language skills. Arabic a plus',
        country: 'DE',
        requires: false,
        advantage: true,
    },
    {
        label: '2a advantage — "local language is a plus"',
        title: 'Consultant',
        desc: 'Multi-lingual: Proficient in English. One of the most spoken EMEA local language is a plus i.e. French, Italian, Spanish, Dutch, Arabic.',
        country: 'NL',
        requires: false,
        advantage: true,
    },
    //{
    //  label: '2a advantage — "Dutch ... preferred"',
    //  title: 'Consultant',
    //  desc: 'High level of English (written and oral) is required, Dutch speaking skills on top of that are preferred.',
    //  country: 'NL',
    //  requires: false,
    //  advantage: true,
    //},
    {
        label: '2a advantage — "Dutch ... added value"',
        title: 'Consultant',
        desc: 'Additional fluent language skills in the local language Dutch are of great added value.',
        country: 'NL',
        requires: false,
        advantage: true,
    },
    {
        label: '2a advantage — "additional Dutch is considered a plus"',
        title: 'Consultant',
        desc: 'Fluency in English (additional Dutch is considered a plus).',
        country: 'NL',
        requires: false,
        advantage: true,
    },
    {
        label: '2a advantage — "Dutch is preferable"',
        title: 'Consultant',
        desc: 'Language: fluent English and Dutch is preferable',
        country: 'NL',
        requires: false,
        advantage: true,
    },

    // ── Phase 2a: "knowledge of X" adjective guard ────────────────────────────

    {
        label: '2a adjective — "knowledge of Dutch law" not a language signal',
        title: 'Legal Counsel',
        desc: 'Knowledge of Dutch law and corporate regulations is required.',
        country: 'NL',
        requires: false,
        advantage: false,
    },
    {
        label: '2a adjective — "knowledge of German market" not a language signal',
        title: 'Sales Director',
        desc: 'Knowledge of German market dynamics is essential.',
        country: 'DE',
        requires: false,
        advantage: false,
    },
    {
        label: '2a adjective — "knowledge of Dutch" alone IS a language signal',
        title: 'Support Engineer',
        desc: 'Knowledge of Dutch required for client calls.',
        country: 'NL',
        requires: true,
        advantage: false,
    },

    // ── Phase 2a: Negation — "or English" downgrades to no signal ─────────────

    {
        label: '2a negation-none — "fluent in Finnish or English" → no signal',
        title: 'Engineer',
        desc: 'You should be fluent in Finnish or English.',
        country: 'FI',
        requires: false,
        advantage: false,
    },
    {
        label: '2a negation-none — "Finnish fluency or English" → no signal',
        title: 'Analyst',
        desc: 'Finnish fluency or English accepted.',
        country: 'FI',
        requires: false,
        advantage: false,
    },
    {
        label: '2a negation-none — "Fluent German or English" → no signal',
        title: 'Consultant',
        desc: 'Language skills: Fluent German or English',
        country: 'DE',
        requires: false,
        advantage: false,
    },

    // ── Phase 2a: Negation — "not required / nice-to-have" downgrades to advantage

    {
        label: '2a negation-advantage — "Finnish not required" → advantage',
        title: 'Business Developer',
        desc: 'Finnish skills not required but appreciated.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '2a negation-advantage — "Swedish language skills is a plus" via DIRECT_ADVANTAGE_SUFFIX',
        title: 'Customer Success Manager',
        desc: 'Fluent knowledge skills in English language, both oral and written, Swedish language skills is a plus.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '2a negation-advantage — "Swedish language skills are considered a plus"',
        title: 'Account Manager',
        desc: 'Swedish language skills are considered a plus.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '2a negation-advantage — "fluent Finnish, nice-to-have" → advantage',
        title: 'Support Lead',
        desc: 'Fluent Finnish, nice-to-have but not compulsory.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '2a negation-NOT — "nice-to-have Skills:" section heading must not negate prior requirement',
        title: 'Software Engineer',
        desc: 'Language Skills: Fluency both written and spoken in English and German\nNice-to-have Skills: Experience with Kubernetes.',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a adv-overlap — "Dutch speaking skills on top of that are preferred" → advantage',
        title: 'Account Executive',
        desc: 'High level of English (written and oral) is required, Dutch speaking skills on top of that are preferred.',
        country: 'NL',
        requires: false,
        advantage: true,
    },
    {
        label: '2a negation-advantage — "communication skills in German are desirable" → advantage',
        title: 'Financial Analyst',
        desc: 'Fluent written and oral communication skills in German are desirable.',
        country: 'DE',
        requires: false,
        advantage: true,
    },

    // ── Phase 2a: Advantage prefix — "bonus points if / plus if" ─────────────

    {
        label: '2a advantage-prefix — "bonus points if you speak Finnish"',
        title: 'Customer Success',
        desc: 'Bonus points if you speak Finnish.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '2a advantage-prefix — "it\'s a plus if you speak Finnish"',
        title: 'Sales Executive',
        desc: "It's a plus if you speak Finnish.",
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '2a advantage-prefix — "nice to have if you speak Finnish"',
        title: 'Solutions Consultant',
        desc: 'Nice to have if you speak Finnish.',
        country: 'FI',
        requires: false,
        advantage: true,
    },
    {
        label: '2a advantage-prefix — "would be great if you speak Finnish"',
        title: 'Partner Manager',
        desc: 'Would be great if you speak Finnish.',
        country: 'FI',
        requires: false,
        advantage: true,
    },

    // ── Phase 2a-nordic: Group Nordic requirement phrases ─────────────────────

    {
        label: '2a-nordic — "fluent in English and at least one Nordic language"',
        title: 'Regional Manager',
        desc: 'You must be fluent in English and at least one Nordic language.',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a-nordic — "proficiency in English and one of the Nordic languages"',
        title: 'Account Director',
        desc: 'We require proficiency in English and one of the Nordic languages.',
        country: 'NO',
        requires: true,
        advantage: false,
    },
    {
        label: '2a-nordic — "in English and in one Nordic language"',
        title: 'Communications Lead',
        desc: 'You will communicate in English and in one Nordic language.',
        country: 'FI',
        requires: true,
        advantage: false,
    },
    {
        label: '2a-nordic — "fluency in English and a Scandinavian language"',
        title: 'Head of Sales',
        desc: 'We expect fluency in English and a Scandinavian language.',
        country: 'DK',
        requires: true,
        advantage: false,
    },
    {
        label: '2a-nordic — "English and at least one Scandinavian language"',
        title: 'Territory Manager',
        desc: 'English and at least one Scandinavian language is required.',
        country: 'NO',
        requires: true,
        advantage: false,
    },
    {
        label: '2a-nordic — "proficiency in a Nordic language is mandatory"',
        title: 'Client Manager',
        desc: 'You need to be Nordic-based and have fluency in English; proficiency in a Nordic language is mandatory.',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a-nordic — "proficiency in at least one Nordic language is required"',
        title: 'Account Executive',
        desc: 'Proficiency in at least one Nordic language is required for this role.',
        country: 'SE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a-nordic — "Nordic language skills are required" wins over cross-language advantage',
        title: 'Account Manager',
        desc: 'Strong English and Nordic language skills are required. German language skills are considered a plus.',
        country: 'SE',
        requires: true,
        advantage: false,
    },

    // ── Phase 2a-cross: Cross-language (non-country language in description) ──

    {
        label: '2a-cross — "fluent Norwegian required" on Latvia job',
        title: 'Nordic Sales Manager',
        desc: 'Fluent Norwegian required for this Nordic-focused role.',
        country: 'LV',
        requires: true,
        advantage: false,
    },
    {
        label: '2a-cross — "Swedish language skills" on Germany job',
        title: 'Nordic Account Manager',
        desc: 'Swedish language skills required for Scandinavian clients.',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a-cross — "Dutch is an advantage" on Sweden job',
        title: 'Benelux Sales Representative',
        desc: 'Based in Stockholm. Dutch is an advantage for this Benelux role.',
        country: 'SE',
        requires: false,
        advantage: true,
    },
    {
        label: '2a-cross — requirement wins over co-present cross advantage',
        title: 'Senior Consultant',
        // "excellent written and spoken Dutch" is a requirement; "additional languages is an asset"
        // is a generic advantage phrase — the requirement must win.
        desc: 'You must have excellent written and spoken Dutch. Additional languages is an asset.',
        country: 'DE',
        requires: true,
        advantage: false,
    },

    // ── Phase 2b: Location-conditional requirement ────────────────────────────

    // ── "Fluent in one Scandinavian language" requirement ─────────────────────
    {
        label: '2a-nordic — "fluent in one Scandinavian language and English" → SE required',
        title: 'Account Manager',
        desc: 'Fluent in one Scandinavian language and English is a requirement. Strong communication skills in English and a Scandinavian language',
        country: 'SE',
        requires: true,
        advantage: false,
    },

    // ── Multi-language country requirement/advantage ordering (2026-07-31) ────
    // CH/BE/LU track multiple languages per country. A requirement signal for
    // one language must win even when an advantage signal for a DIFFERENT
    // country language appears earlier in the text — see
    // languageHasGenuineRequirement / anyGenuineRequirement in language.ts.
    {
        label: '2a — hyphenated "German-native" → CH required',
        title: 'Engineer',
        desc: 'Swiss German-native, English fluent speaker',
        country: 'CH',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Very good French skills; German skills is an advantage" → CH required (French wins over German advantage)',
        title: 'Engineer',
        desc: 'Very good French and English skills; German skills is an advantage',
        country: 'CH',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Fluent in English and French. Dutch is considered an asset." → BE required (French wins over Dutch advantage)',
        title: 'Engineer',
        desc: 'Fluent in English and French. Dutch is considered an asset.',
        country: 'BE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Fluency both in French (C1) and English (B2)...Dutch is an asset." → BE required',
        title: 'Engineer',
        desc: 'Fluency both in French (C1) and English (B2) (Written, read & spoken). Dutch is an asset.',
        country: 'BE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "You speak both French and English (German is an asset)" → BE required',
        title: 'Engineer',
        desc: 'You speak both French and English (German is an asset)',
        country: 'BE',
        requires: true,
        advantage: false,
    },

    // ── "{lang} proficient" requirement (2026-07-31) ───────────────────────────
    {
        label: '2a — "Language: French proficient, English good level" → FR required',
        title: 'Engineer',
        desc: 'Language: French proficient, English good level',
        country: 'FR',
        requires: true,
        advantage: false,
    },

    // ── Baseline requirement phrasing sanity checks (2026-07-31) ───────────────
    {
        label: '2a — "Fluent in written and spoken French and English" → FR required',
        title: 'Engineer',
        desc: 'Fluent in written and spoken French and English',
        country: 'FR',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Fluent in written and spoken German and English" → DE required',
        title: 'Engineer',
        desc: 'Fluent in written and spoken German and English',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Strong knowledge of French and English." → FR required',
        title: 'Engineer',
        desc: 'Strong knowledge of French and English.',
        country: 'FR',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Fluent German and English skills, and Finnish language skills are an advantage" → DE required',
        title: 'Engineer',
        desc: 'Fluent German and English skills, and Finnish language skills are an advantage',
        country: 'DE',
        requires: true,
        advantage: false,
    },

    // ── "{lang1}, {lang2}, and English: proficiency required for all N languages" (2026-08-03) ─
    {
        label: '2a — "Dutch, French, and English: ...required for all three languages" → NL required',
        title: 'Engineer',
        desc: 'Dutch, French, and English: Professional working proficiency is required for all three languages.',
        country: 'NL',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Dutch, French, and English: ...required for all three languages" → BE required',
        title: 'Engineer',
        desc: 'Dutch, French, and English: Professional working proficiency is required for all three languages.',
        country: 'BE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Dutch, French, and English: ...required for all three languages" → DE required even though neither listed language is German (matched language, not country language, drives the verdict)',
        title: 'Engineer',
        desc: 'Dutch, French, and English: Professional working proficiency is required for all three languages.',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "English, English, and English: ...required for all three languages" → no other language named, FR NOT required',
        title: 'Engineer',
        desc: 'English, English, and English: Professional working proficiency is required for all three languages.',
        country: 'FR',
        requires: false,
        advantage: false,
    },
    {
        label: '2a — "Very good French skills; German skills is an advantage" → BE required (French wins over German advantage, non-CH multi-language country)',
        title: 'Engineer',
        desc: 'Very good French and English skills; German skills is an advantage',
        country: 'BE',
        requires: true,
        advantage: false,
    },

    // ── Compound-mention advantage misattribution across languages (2026-08-06) ─
    // buildAdvantageRegex's compound-mention gap tolerance (up to 8 words) used to
    // let e.g. "proficiency in Dutch" reach across "and English" to steal French's
    // advantage phrase, wrongly downgrading a genuine Dutch requirement to "advantage".
    {
        label: '2a — "Fluency in English and Dutch" → BE required',
        title: 'Engineer',
        desc: 'Fluency in English and Dutch',
        country: 'BE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Language: Proficiency in Dutch and English (French is considered an asset)." → BE required (French advantage phrase not misattributed to Dutch)',
        title: 'Engineer',
        desc: 'Language: Proficiency in Dutch and English (French is considered an asset).',
        country: 'BE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Language proficiency in Dutch and English (French is considered an asset)" → BE required (no trailing period)',
        title: 'Engineer',
        desc: 'Language proficiency in Dutch and English (French is considered an asset)',
        country: 'BE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "A native speaker in French or Dutch and professional working proficiency in English" → BE required',
        title: 'Engineer',
        desc: 'A native speaker in French or Dutch and professional working proficiency in English',
        country: 'BE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Fluent in English and at least French or Dutch" → BE required',
        title: 'Engineer',
        desc: 'Fluent in English and at least French or Dutch',
        country: 'BE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "Fluent in English and a very good level of Dutch are mandatory. French will be a plus." → BE required',
        title: 'Engineer',
        desc: 'Fluent in English and a very good level of Dutch are mandatory. French will be a plus.',
        country: 'BE',
        requires: true,
        advantage: false,
    },

    // ── More requirement/advantage phrasings (2026-08-06) ───────────────────────
    {
        label: '2a — "Fluent in English; Dutch and French" → BE required (semicolon-separated list)',
        title: 'Engineer',
        desc: 'Fluent in English; Dutch and French',
        country: 'BE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "A native speaker Dutch and professional working proficiency in English" → NL required (no preposition)',
        title: 'Engineer',
        desc: 'A native speaker Dutch and professional working proficiency in English',
        country: 'NL',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "A native speaker of French or Dutch and professional working proficiency in English" → BE required ("of" preposition)',
        title: 'Engineer',
        desc: 'A native speaker of French or Dutch and professional working proficiency in English',
        country: 'BE',
        requires: true,
        advantage: false,
    },
    {
        label: '2a — "...German at fluent level is mandatory;" → DE required',
        title: 'Engineer',
        desc: 'Strong communication and presentation skills in English (written and spoken); German at fluent level is mandatory;',
        country: 'DE',
        requires: true,
        advantage: false,
    },
    {
        label: '1b — "...French or German considered a strong advantage." → CH advantage (bare "considered", no "is")',
        title: 'Engineer',
        desc: 'fluency in English required, with French or German considered a strong advantage.',
        country: 'CH',
        requires: false,
        advantage: true,
    },
    {
        label: '1b — "Professional proficiency in English (knowledge of additional EU languages is a plus)." → DE advantage (generic "additional languages", no language named)',
        title: 'Engineer',
        desc: 'Professional proficiency in English (knowledge of additional EU languages is a plus).',
        country: 'DE',
        requires: false,
        advantage: true,
    },
];
