export interface CountryInfo {
  name: string;
  code: string;
  slug: string;
}

// Keyed by lowercase, trimmed country name or common abbreviation.
const COUNTRY_MAP: Record<string, CountryInfo> = {
  // Nordics
  'finland': { name: 'Finland', code: 'FI', slug: 'finland' },
  'suomi': { name: 'Finland', code: 'FI', slug: 'finland' },
  'fin': { name: 'Finland', code: 'FI', slug: 'finland' },
  'fi': { name: 'Finland', code: 'FI', slug: 'finland' },
  'denmark': { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'danmark': { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'dnk': { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'dk': { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'iceland': { name: 'Iceland', code: 'IS', slug: 'iceland' },
  'island': { name: 'Iceland', code: 'IS', slug: 'iceland' },
  'isl': { name: 'Iceland', code: 'IS', slug: 'iceland' },
  'is': { name: 'Iceland', code: 'IS', slug: 'iceland' },
  'norway': { name: 'Norway', code: 'NO', slug: 'norway' },
  'norge': { name: 'Norway', code: 'NO', slug: 'norway' },
  'nor': { name: 'Norway', code: 'NO', slug: 'norway' },
  'no': { name: 'Norway', code: 'NO', slug: 'norway' },
  'sweden': { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'sverige': { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'swe': { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'se': { name: 'Sweden', code: 'SE', slug: 'sweden' },
  // Baltics
  'estonia': { name: 'Estonia', code: 'EE', slug: 'estonia' },
  'eesti': { name: 'Estonia', code: 'EE', slug: 'estonia' },
  'est': { name: 'Estonia', code: 'EE', slug: 'estonia' },
  'ee': { name: 'Estonia', code: 'EE', slug: 'estonia' },
  'latvia': { name: 'Latvia', code: 'LV', slug: 'latvia' },
  'latvija': { name: 'Latvia', code: 'LV', slug: 'latvia' },
  'lva': { name: 'Latvia', code: 'LV', slug: 'latvia' },
  'lv': { name: 'Latvia', code: 'LV', slug: 'latvia' },
  'lithuania': { name: 'Lithuania', code: 'LT', slug: 'lithuania' },
  'lietuva': { name: 'Lithuania', code: 'LT', slug: 'lithuania' },
  'ltu': { name: 'Lithuania', code: 'LT', slug: 'lithuania' },
  'lt': { name: 'Lithuania', code: 'LT', slug: 'lithuania' },
  // DACH
  'austria': { name: 'Austria', code: 'AT', slug: 'austria' },
  'österreich': { name: 'Austria', code: 'AT', slug: 'austria' },
  'osterreich': { name: 'Austria', code: 'AT', slug: 'austria' },
  'aut': { name: 'Austria', code: 'AT', slug: 'austria' },
  'germany': { name: 'Germany', code: 'DE', slug: 'germany' },
  'deutschland': { name: 'Germany', code: 'DE', slug: 'germany' },
  'deu': { name: 'Germany', code: 'DE', slug: 'germany' },
  'de': { name: 'Germany', code: 'DE', slug: 'germany' },
  'switzerland': { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  'schweiz': { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  'suisse': { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  'che': { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  // Western Europe
  'andorra': { name: 'Andorra', code: 'AD', slug: 'andorra' },
  'belgium': { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'belgique': { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'belgië': { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'belgie': { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'bel': { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'france': { name: 'France', code: 'FR', slug: 'france' },
  'fra': { name: 'France', code: 'FR', slug: 'france' },
  'italy': { name: 'Italy', code: 'IT', slug: 'italy' },
  'italia': { name: 'Italy', code: 'IT', slug: 'italy' },
  'ita': { name: 'Italy', code: 'IT', slug: 'italy' },
  'luxembourg': { name: 'Luxembourg', code: 'LU', slug: 'luxembourg' },
  'lux': { name: 'Luxembourg', code: 'LU', slug: 'luxembourg' },
  'monaco': { name: 'Monaco', code: 'MC', slug: 'monaco' },
  'netherlands': { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'the netherlands': { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'holland': { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'nederland': { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'nld': { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'nl': { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'san marino': { name: 'San Marino', code: 'SM', slug: 'san-marino' },
  'spain': { name: 'Spain', code: 'ES', slug: 'spain' },
  'españa': { name: 'Spain', code: 'ES', slug: 'spain' },
  'espana': { name: 'Spain', code: 'ES', slug: 'spain' },
  'esp': { name: 'Spain', code: 'ES', slug: 'spain' },
  'portugal': { name: 'Portugal', code: 'PT', slug: 'portugal' },
  'prt': { name: 'Portugal', code: 'PT', slug: 'portugal' },
  // British Isles
  'ireland': { name: 'Ireland', code: 'IE', slug: 'ireland' },
  'irl': { name: 'Ireland', code: 'IE', slug: 'ireland' },
  'scotland': { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'united kingdom': { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'uk': { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'great britain': { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'gbr': { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'england': { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'wales': { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  // Central/Eastern Europe
  'albania': { name: 'Albania', code: 'AL', slug: 'albania' },
  'alb': { name: 'Albania', code: 'AL', slug: 'albania' },
  'belarus': { name: 'Belarus', code: 'BY', slug: 'belarus' },
  'bosnia': { name: 'Bosnia and Herzegovina', code: 'BA', slug: 'bosnia-and-herzegovina' },
  'bosnia and herzegovina': { name: 'Bosnia and Herzegovina', code: 'BA', slug: 'bosnia-and-herzegovina' },
  'bih': { name: 'Bosnia and Herzegovina', code: 'BA', slug: 'bosnia-and-herzegovina' },
  'bulgaria': { name: 'Bulgaria', code: 'BG', slug: 'bulgaria' },
  'bgr': { name: 'Bulgaria', code: 'BG', slug: 'bulgaria' },
  'croatia': { name: 'Croatia', code: 'HR', slug: 'croatia' },
  'hrvatska': { name: 'Croatia', code: 'HR', slug: 'croatia' },
  'hrv': { name: 'Croatia', code: 'HR', slug: 'croatia' },
  'czech republic': { name: 'Czech Republic', code: 'CZ', slug: 'czech-republic' },
  'czechia': { name: 'Czech Republic', code: 'CZ', slug: 'czech-republic' },
  'česká republika': { name: 'Czech Republic', code: 'CZ', slug: 'czech-republic' },
  'ceska republika': { name: 'Czech Republic', code: 'CZ', slug: 'czech-republic' },
  'cze': { name: 'Czech Republic', code: 'CZ', slug: 'czech-republic' },
  'georgia': { name: 'Georgia', code: 'GE', slug: 'georgia' },
  'hungary': { name: 'Hungary', code: 'HU', slug: 'hungary' },
  'kosovo': { name: 'Kosovo', code: 'XK', slug: 'kosovo' },
  'liechtenstein': { name: 'Liechtenstein', code: 'LI', slug: 'liechtenstein' },
  'magyarország': { name: 'Hungary', code: 'HU', slug: 'hungary' },
  'magyarorszag': { name: 'Hungary', code: 'HU', slug: 'hungary' },
  'hun': { name: 'Hungary', code: 'HU', slug: 'hungary' },
  'montenegro': { name: 'Montenegro', code: 'ME', slug: 'montenegro' },
  'mne': { name: 'Montenegro', code: 'ME', slug: 'montenegro' },
  'north macedonia': { name: 'North Macedonia', code: 'MK', slug: 'north-macedonia' },
  'macedonia': { name: 'North Macedonia', code: 'MK', slug: 'north-macedonia' },
  'mkd': { name: 'North Macedonia', code: 'MK', slug: 'north-macedonia' },
  'moldova': { name: 'Moldova', code: 'MD', slug: 'moldova' },
  'poland': { name: 'Poland', code: 'PL', slug: 'poland' },
  'polska': { name: 'Poland', code: 'PL', slug: 'poland' },
  'pol': { name: 'Poland', code: 'PL', slug: 'poland' },
  'romania': { name: 'Romania', code: 'RO', slug: 'romania' },
  'rou': { name: 'Romania', code: 'RO', slug: 'romania' },
  'russia': { name: 'Russia', code: 'RU', slug: 'russia' },
  'serbia': { name: 'Serbia', code: 'RS', slug: 'serbia' },
  'srbija': { name: 'Serbia', code: 'RS', slug: 'serbia' },
  'srb': { name: 'Serbia', code: 'RS', slug: 'serbia' },
  'slovakia': { name: 'Slovakia', code: 'SK', slug: 'slovakia' },
  'slovensko': { name: 'Slovakia', code: 'SK', slug: 'slovakia' },
  'svk': { name: 'Slovakia', code: 'SK', slug: 'slovakia' },
  'slovenia': { name: 'Slovenia', code: 'SI', slug: 'slovenia' },
  'svn': { name: 'Slovenia', code: 'SI', slug: 'slovenia' },
  'ukraine': { name: 'Ukraine', code: 'UA', slug: 'ukraine' },
  // Southern/SE Europe
  'cyprus': { name: 'Cyprus', code: 'CY', slug: 'cyprus' },
  'greece': { name: 'Greece', code: 'GR', slug: 'greece' },
  'hellas': { name: 'Greece', code: 'GR', slug: 'greece' },
  'malta': { name: 'Malta', code: 'MT', slug: 'malta' },
  'turkey': { name: 'Turkey', code: 'TR', slug: 'turkey' },
  'türkiye': { name: 'Turkey', code: 'TR', slug: 'turkey' },
  'turkiye': { name: 'Turkey', code: 'TR', slug: 'turkey' },
  // North America
  'barbados': { name: 'Barbados', code: 'BB', slug: 'barbados' },
  'belize': { name: 'Belize', code: 'BZ', slug: 'belize' },
  'canada': { name: 'Canada', code: 'CA', slug: 'canada' },
  'costa rica': { name: 'Costa Rica', code: 'CR', slug: 'costa-rica' },
  'cuba': { name: 'Cuba', code: 'CU', slug: 'cuba' },
  'dominican republic': { name: 'Dominican Republic', code: 'DO', slug: 'dominican-republic' },
  'el salvador': { name: 'El Salvador', code: 'SV', slug: 'el-salvador' },
  'guatemala': { name: 'Guatemala', code: 'GT', slug: 'guatemala' },
  'haiti': { name: 'Haiti', code: 'HT', slug: 'haiti' },
  'honduras': { name: 'Honduras', code: 'HN', slug: 'honduras' },
  'jamaica': { name: 'Jamaica', code: 'JM', slug: 'jamaica' },
  'mexico': { name: 'Mexico', code: 'MX', slug: 'mexico' },
  'méxico': { name: 'Mexico', code: 'MX', slug: 'mexico' },
  'nicaragua': { name: 'Nicaragua', code: 'NI', slug: 'nicaragua' },
  'panama': { name: 'Panama', code: 'PA', slug: 'panama' },
  'puerto rico': { name: 'Puerto Rico', code: 'PR', slug: 'puerto-rico' },
  'trinidad and tobago': { name: 'Trinidad and Tobago', code: 'TT', slug: 'trinidad-and-tobago' },
  'trinidad': { name: 'Trinidad and Tobago', code: 'TT', slug: 'trinidad-and-tobago' },
  'united states': { name: 'United States', code: 'US', slug: 'united-states' },
  'united states of america': { name: 'United States', code: 'US', slug: 'united-states' },
  'usa': { name: 'United States', code: 'US', slug: 'united-states' },
  'u.s.a.': { name: 'United States', code: 'US', slug: 'united-states' },
  'u.s.': { name: 'United States', code: 'US', slug: 'united-states' },
  // South America
  'argentina': { name: 'Argentina', code: 'AR', slug: 'argentina' },
  'bolivia': { name: 'Bolivia', code: 'BO', slug: 'bolivia' },
  'brasil': { name: 'Brazil', code: 'BR', slug: 'brazil' },
  'brazil': { name: 'Brazil', code: 'BR', slug: 'brazil' },
  'chile': { name: 'Chile', code: 'CL', slug: 'chile' },
  'colombia': { name: 'Colombia', code: 'CO', slug: 'colombia' },
  'ecuador': { name: 'Ecuador', code: 'EC', slug: 'ecuador' },
  'guyana': { name: 'Guyana', code: 'GY', slug: 'guyana' },
  'paraguay': { name: 'Paraguay', code: 'PY', slug: 'paraguay' },
  'peru': { name: 'Peru', code: 'PE', slug: 'peru' },
  'perú': { name: 'Peru', code: 'PE', slug: 'peru' },
  'suriname': { name: 'Suriname', code: 'SR', slug: 'suriname' },
  'uruguay': { name: 'Uruguay', code: 'UY', slug: 'uruguay' },
  'venezuela': { name: 'Venezuela', code: 'VE', slug: 'venezuela' },
  // Asia
  'afghanistan': { name: 'Afghanistan', code: 'AF', slug: 'afghanistan' },
  'armenia': { name: 'Armenia', code: 'AM', slug: 'armenia' },
  'azerbaijan': { name: 'Azerbaijan', code: 'AZ', slug: 'azerbaijan' },  
  'bangladesh': { name: 'Bangladesh', code: 'BD', slug: 'bangladesh' },
  'bhutan': { name: 'Bhutan', code: 'BT', slug: 'bhutan' },
  'brunei': { name: 'Brunei', code: 'BN', slug: 'brunei' },
  'cambodia': { name: 'Cambodia', code: 'KH', slug: 'cambodia' },
  'china': { name: 'China', code: 'CN', slug: 'china' },
  'hong kong': { name: 'Hong Kong', code: 'HK', slug: 'hong-kong' },
  'india': { name: 'India', code: 'IN', slug: 'india' },
  'indonesia': { name: 'Indonesia', code: 'ID', slug: 'indonesia' },
  'japan': { name: 'Japan', code: 'JP', slug: 'japan' },
  'kazakhstan': { name: 'Kazakhstan', code: 'KZ', slug: 'kazakhstan' },
  'korea': { name: 'South Korea', code: 'KR', slug: 'south-korea' },
  'kyrgyzstan': { name: 'Kyrgyzstan', code: 'KG', slug: 'kyrgyzstan' },
  'laos': { name: 'Laos', code: 'LA', slug: 'laos' },
  'malaysia': { name: 'Malaysia', code: 'MY', slug: 'malaysia' },
  'maldives': { name: 'Maldives', code: 'MV', slug: 'maldives' },
  'mongolia': { name: 'Mongolia', code: 'MN', slug: 'mongolia' },
  'myanmar': { name: 'Myanmar', code: 'MM', slug: 'myanmar' },
  'burma': { name: 'Myanmar', code: 'MM', slug: 'myanmar' },
  'nepal': { name: 'Nepal', code: 'NP', slug: 'nepal' },
  'pakistan': { name: 'Pakistan', code: 'PK', slug: 'pakistan' },
  'papua new guinea': { name: 'Papua New Guinea', code: 'PG', slug: 'papua-new-guinea' },
  'philippines': { name: 'Philippines', code: 'PH', slug: 'philippines' },
  'singapore': { name: 'Singapore', code: 'SG', slug: 'singapore' },
  'south korea': { name: 'South Korea', code: 'KR', slug: 'south-korea' },
  'sri lanka': { name: 'Sri Lanka', code: 'LK', slug: 'sri-lanka' },
  'taiwan': { name: 'Taiwan', code: 'TW', slug: 'taiwan' },
  'tajikistan': { name: 'Tajikistan', code: 'TJ', slug: 'tajikistan' },
  'thailand': { name: 'Thailand', code: 'TH', slug: 'thailand' },
  'timor-leste': { name: 'Timor-Leste', code: 'TL', slug: 'timor-leste' },
  'east timor': { name: 'Timor-Leste', code: 'TL', slug: 'timor-leste' },
  'turkmenistan': { name: 'Turkmenistan', code: 'TM', slug: 'turkmenistan' },
  'uzbekistan': { name: 'Uzbekistan', code: 'UZ', slug: 'uzbekistan' },
  'vietnam': { name: 'Vietnam', code: 'VN', slug: 'vietnam' },
  'viet nam': { name: 'Vietnam', code: 'VN', slug: 'vietnam' },
  // Middle East
  'bahrain': { name: 'Bahrain', code: 'BH', slug: 'bahrain' },
  'iran': { name: 'Iran', code: 'IR', slug: 'iran' },
  'iraq': { name: 'Iraq', code: 'IQ', slug: 'iraq' },
  'israel': { name: 'Israel', code: 'IL', slug: 'israel' },
  'jordan': { name: 'Jordan', code: 'JO', slug: 'jordan' },
  'kuwait': { name: 'Kuwait', code: 'KW', slug: 'kuwait' },
  'lebanon': { name: 'Lebanon', code: 'LB', slug: 'lebanon' },
  'oman': { name: 'Oman', code: 'OM', slug: 'oman' },
  'palestine': { name: 'Palestine', code: 'PS', slug: 'palestine' },
  'qatar': { name: 'Qatar', code: 'QA', slug: 'qatar' },
  'saudi arabia': { name: 'Saudi Arabia', code: 'SA', slug: 'saudi-arabia' },
  'syria': { name: 'Syria', code: 'SY', slug: 'syria' },
  'united arab emirates': { name: 'United Arab Emirates', code: 'AE', slug: 'united-arab-emirates' },
  'uae': { name: 'United Arab Emirates', code: 'AE', slug: 'united-arab-emirates' },
  'yemen': { name: 'Yemen', code: 'YE', slug: 'yemen' },
  // Africa
  'algeria': { name: 'Algeria', code: 'DZ', slug: 'algeria' },
  'angola': { name: 'Angola', code: 'AO', slug: 'angola' },
  'benin': { name: 'Benin', code: 'BJ', slug: 'benin' },
  'botswana': { name: 'Botswana', code: 'BW', slug: 'botswana' },
  'burkina faso': { name: 'Burkina Faso', code: 'BF', slug: 'burkina-faso' },
  'cameroon': { name: 'Cameroon', code: 'CM', slug: 'cameroon' },
  'cape verde': { name: 'Cape Verde', code: 'CV', slug: 'cape-verde' },
  'cabo verde': { name: 'Cape Verde', code: 'CV', slug: 'cape-verde' },
  'central african republic': { name: 'Central African Republic', code: 'CF', slug: 'central-african-republic' },
  'chad': { name: 'Chad', code: 'TD', slug: 'chad' },
  'comoros': { name: 'Comoros', code: 'KM', slug: 'comoros' },
  "côte d'ivoire": { name: 'Ivory Coast', code: 'CI', slug: 'ivory-coast' },
  "cote d'ivoire": { name: 'Ivory Coast', code: 'CI', slug: 'ivory-coast' },
  'democratic republic of the congo': { name: 'Democratic Republic of the Congo', code: 'CD', slug: 'democratic-republic-of-the-congo' },
  'dr congo': { name: 'Democratic Republic of the Congo', code: 'CD', slug: 'democratic-republic-of-the-congo' },
  'drc': { name: 'Democratic Republic of the Congo', code: 'CD', slug: 'democratic-republic-of-the-congo' },
  'djibouti': { name: 'Djibouti', code: 'DJ', slug: 'djibouti' },
  'equatorial guinea': { name: 'Equatorial Guinea', code: 'GQ', slug: 'equatorial-guinea' },
  'egypt': { name: 'Egypt', code: 'EG', slug: 'egypt' },
  'eritrea': { name: 'Eritrea', code: 'ER', slug: 'eritrea' },
  'eswatini': { name: 'Eswatini', code: 'SZ', slug: 'eswatini' },
  'ethiopia': { name: 'Ethiopia', code: 'ET', slug: 'ethiopia' },
  'gabon': { name: 'Gabon', code: 'GA', slug: 'gabon' },
  'gambia': { name: 'Gambia', code: 'GM', slug: 'gambia' },
  'the gambia': { name: 'Gambia', code: 'GM', slug: 'gambia' },
  'ghana': { name: 'Ghana', code: 'GH', slug: 'ghana' },
  'guinea': { name: 'Guinea', code: 'GN', slug: 'guinea' },
  'guinea-bissau': { name: 'Guinea-Bissau', code: 'GW', slug: 'guinea-bissau' },
  "ivory coast": { name: 'Ivory Coast', code: 'CI', slug: 'ivory-coast' },
  'kenya': { name: 'Kenya', code: 'KE', slug: 'kenya' },
  'lesotho': { name: 'Lesotho', code: 'LS', slug: 'lesotho' },
  'liberia': { name: 'Liberia', code: 'LR', slug: 'liberia' },
  'libya': { name: 'Libya', code: 'LY', slug: 'libya' },
  'madagascar': { name: 'Madagascar', code: 'MG', slug: 'madagascar' },
  'malawi': { name: 'Malawi', code: 'MW', slug: 'malawi' },
  'mali': { name: 'Mali', code: 'ML', slug: 'mali' },
  'mauritania': { name: 'Mauritania', code: 'MR', slug: 'mauritania' },
  'mauritius': { name: 'Mauritius', code: 'MU', slug: 'mauritius' },
  'morocco': { name: 'Morocco', code: 'MA', slug: 'morocco' },
  'mozambique': { name: 'Mozambique', code: 'MZ', slug: 'mozambique' },
  'namibia': { name: 'Namibia', code: 'NA', slug: 'namibia' },
  'niger': { name: 'Niger', code: 'NE', slug: 'niger' },
  'nigeria': { name: 'Nigeria', code: 'NG', slug: 'nigeria' },
  'republic of the congo': { name: 'Republic of the Congo', code: 'CG', slug: 'republic-of-the-congo' },
  'congo': { name: 'Republic of the Congo', code: 'CG', slug: 'republic-of-the-congo' },
  'rwanda': { name: 'Rwanda', code: 'RW', slug: 'rwanda' },
  'sao tome and principe': { name: 'São Tomé and Príncipe', code: 'ST', slug: 'sao-tome-and-principe' },
  'senegal': { name: 'Senegal', code: 'SN', slug: 'senegal' },
  'seychelles': { name: 'Seychelles', code: 'SC', slug: 'seychelles' },
  'sierra leone': { name: 'Sierra Leone', code: 'SL', slug: 'sierra-leone' },
  'somalia': { name: 'Somalia', code: 'SO', slug: 'somalia' },
  'south africa': { name: 'South Africa', code: 'ZA', slug: 'south-africa' },
  'south sudan': { name: 'South Sudan', code: 'SS', slug: 'south-sudan' },
  'sudan': { name: 'Sudan', code: 'SD', slug: 'sudan' },
  'swaziland': { name: 'Eswatini', code: 'SZ', slug: 'eswatini' },
  'tanzania': { name: 'Tanzania', code: 'TZ', slug: 'tanzania' },
  'togo': { name: 'Togo', code: 'TG', slug: 'togo' },
  'tunisia': { name: 'Tunisia', code: 'TN', slug: 'tunisia' },
  'uganda': { name: 'Uganda', code: 'UG', slug: 'uganda' },
  'zambia': { name: 'Zambia', code: 'ZM', slug: 'zambia' },
  'zimbabwe': { name: 'Zimbabwe', code: 'ZW', slug: 'zimbabwe' },
  // Oceania
  'australia': { name: 'Australia', code: 'AU', slug: 'australia' },
  'aus': { name: 'Australia', code: 'AU', slug: 'australia' },
  'fiji': { name: 'Fiji', code: 'FJ', slug: 'fiji' },
  'new zealand': { name: 'New Zealand', code: 'NZ', slug: 'new-zealand' },
  'samoa': { name: 'Samoa', code: 'WS', slug: 'samoa' },
  'solomon islands': { name: 'Solomon Islands', code: 'SB', slug: 'solomon-islands' },
  'tonga': { name: 'Tonga', code: 'TO', slug: 'tonga' },
  'vanuatu': { name: 'Vanuatu', code: 'VU', slug: 'vanuatu' },
  // 2-letter ISO codes not already listed above.
  // Needed for Workday venue-code prefix detection, e.g. "USCNC05 - Charlotte" → 'us' → United States.
  // Europe
  'al': { name: 'Albania', code: 'AL', slug: 'albania' },
  'am': { name: 'Armenia', code: 'AM', slug: 'armenia' },
  'at': { name: 'Austria', code: 'AT', slug: 'austria' },
  'az': { name: 'Azerbaijan', code: 'AZ', slug: 'azerbaijan' },
  'ba': { name: 'Bosnia and Herzegovina', code: 'BA', slug: 'bosnia-and-herzegovina' },
  'be': { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'bg': { name: 'Bulgaria', code: 'BG', slug: 'bulgaria' },
  'by': { name: 'Belarus', code: 'BY', slug: 'belarus' },
  'ch': { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  'cy': { name: 'Cyprus', code: 'CY', slug: 'cyprus' },
  'cz': { name: 'Czech Republic', code: 'CZ', slug: 'czech-republic' },
  'es': { name: 'Spain', code: 'ES', slug: 'spain' },
  'fr': { name: 'France', code: 'FR', slug: 'france' },
  'gb': { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'ge': { name: 'Georgia', code: 'GE', slug: 'georgia' },
  'gr': { name: 'Greece', code: 'GR', slug: 'greece' },
  'hr': { name: 'Croatia', code: 'HR', slug: 'croatia' },
  'hu': { name: 'Hungary', code: 'HU', slug: 'hungary' },
  'ie': { name: 'Ireland', code: 'IE', slug: 'ireland' },
  'it': { name: 'Italy', code: 'IT', slug: 'italy' },
  'lu': { name: 'Luxembourg', code: 'LU', slug: 'luxembourg' },
  'md': { name: 'Moldova', code: 'MD', slug: 'moldova' },
  'me': { name: 'Montenegro', code: 'ME', slug: 'montenegro' },
  'mk': { name: 'North Macedonia', code: 'MK', slug: 'north-macedonia' },
  'mt': { name: 'Malta', code: 'MT', slug: 'malta' },
  'pl': { name: 'Poland', code: 'PL', slug: 'poland' },
  'pt': { name: 'Portugal', code: 'PT', slug: 'portugal' },
  'ro': { name: 'Romania', code: 'RO', slug: 'romania' },
  'rs': { name: 'Serbia', code: 'RS', slug: 'serbia' },
  'ru': { name: 'Russia', code: 'RU', slug: 'russia' },
  'si': { name: 'Slovenia', code: 'SI', slug: 'slovenia' },
  'sk': { name: 'Slovakia', code: 'SK', slug: 'slovakia' },
  'tr': { name: 'Turkey', code: 'TR', slug: 'turkey' },
  'ua': { name: 'Ukraine', code: 'UA', slug: 'ukraine' },
  // Americas
  'us': { name: 'United States', code: 'US', slug: 'united-states' },
  'ca': { name: 'Canada', code: 'CA', slug: 'canada' },
  'br': { name: 'Brazil', code: 'BR', slug: 'brazil' },
  'mx': { name: 'Mexico', code: 'MX', slug: 'mexico' },
  'ar': { name: 'Argentina', code: 'AR', slug: 'argentina' },
  'co': { name: 'Colombia', code: 'CO', slug: 'colombia' },
  'cl': { name: 'Chile', code: 'CL', slug: 'chile' },
  // Asia-Pacific
  'au': { name: 'Australia', code: 'AU', slug: 'australia' },
  'nz': { name: 'New Zealand', code: 'NZ', slug: 'new-zealand' },
  'jp': { name: 'Japan', code: 'JP', slug: 'japan' },
  'cn': { name: 'China', code: 'CN', slug: 'china' },
  'in': { name: 'India', code: 'IN', slug: 'india' },
  'sg': { name: 'Singapore', code: 'SG', slug: 'singapore' },
  'kr': { name: 'South Korea', code: 'KR', slug: 'south-korea' },
  'id': { name: 'Indonesia', code: 'ID', slug: 'indonesia' },
  'my': { name: 'Malaysia', code: 'MY', slug: 'malaysia' },
  'th': { name: 'Thailand', code: 'TH', slug: 'thailand' },
  'vn': { name: 'Vietnam', code: 'VN', slug: 'vietnam' },
  'ph': { name: 'Philippines', code: 'PH', slug: 'philippines' },
  'hk': { name: 'Hong Kong', code: 'HK', slug: 'hong-kong' },
  'tw': { name: 'Taiwan', code: 'TW', slug: 'taiwan' },
  'pk': { name: 'Pakistan', code: 'PK', slug: 'pakistan' },
  'kz': { name: 'Kazakhstan', code: 'KZ', slug: 'kazakhstan' },
  // Middle East & Africa
  'il': { name: 'Israel', code: 'IL', slug: 'israel' },
  'ae': { name: 'United Arab Emirates', code: 'AE', slug: 'united-arab-emirates' },
  'sa': { name: 'Saudi Arabia', code: 'SA', slug: 'saudi-arabia' },
  'qa': { name: 'Qatar', code: 'QA', slug: 'qatar' },
  'za': { name: 'South Africa', code: 'ZA', slug: 'south-africa' },
  'eg': { name: 'Egypt', code: 'EG', slug: 'egypt' },
  'ng': { name: 'Nigeria', code: 'NG', slug: 'nigeria' },
  'ke': { name: 'Kenya', code: 'KE', slug: 'kenya' },
  'ma': { name: 'Morocco', code: 'MA', slug: 'morocco' },
  'gh': { name: 'Ghana', code: 'GH', slug: 'ghana' },
  'tz': { name: 'Tanzania', code: 'TZ', slug: 'tanzania' },
};

// City-to-country map for when job APIs return city names instead of country names.
// Only include cities that are unambiguous within the countries this site tracks.
const CITY_MAP: Record<string, CountryInfo> = {
  // ── Finland ──────────────────────────────────────────────────────────────
  'espoo':                    { name: 'Finland', code: 'FI', slug: 'finland' },
  'forssa':                   { name: 'Finland', code: 'FI', slug: 'finland' },
  'heinola':                  { name: 'Finland', code: 'FI', slug: 'finland' },
  'helsinki':                 { name: 'Finland', code: 'FI', slug: 'finland' },
  'helsinki metropolitan area': { name: 'Finland', code: 'FI', slug: 'finland' },
  'huittinen':                { name: 'Finland', code: 'FI', slug: 'finland' },
  'hyvinkää':                 { name: 'Finland', code: 'FI', slug: 'finland' },
  'hyvinkaa':                 { name: 'Finland', code: 'FI', slug: 'finland' },
  'hämeenlinna':              { name: 'Finland', code: 'FI', slug: 'finland' },
  'hameenlinna':              { name: 'Finland', code: 'FI', slug: 'finland' },
  'iisalmi':                  { name: 'Finland', code: 'FI', slug: 'finland' },
  'ilomantsi':                { name: 'Finland', code: 'FI', slug: 'finland' },
  'imatra':                   { name: 'Finland', code: 'FI', slug: 'finland' },
  'joensuu':                  { name: 'Finland', code: 'FI', slug: 'finland' },
  'jyväskylä':                { name: 'Finland', code: 'FI', slug: 'finland' },
  'jyvaskyla':                { name: 'Finland', code: 'FI', slug: 'finland' },
  'jämsä':                    { name: 'Finland', code: 'FI', slug: 'finland' },
  'jamsa':                    { name: 'Finland', code: 'FI', slug: 'finland' },
  'järvenpää':                { name: 'Finland', code: 'FI', slug: 'finland' },
  'jarvenpaa':                { name: 'Finland', code: 'FI', slug: 'finland' },
  'kajaani':                  { name: 'Finland', code: 'FI', slug: 'finland' },
  'kangasala':                { name: 'Finland', code: 'FI', slug: 'finland' },
  'kankaanpää':               { name: 'Finland', code: 'FI', slug: 'finland' },
  'karkkila':                 { name: 'Finland', code: 'FI', slug: 'finland' },
  'karstula':                 { name: 'Finland', code: 'FI', slug: 'finland' },
  'kemi':                     { name: 'Finland', code: 'FI', slug: 'finland' },
  'kerava':                   { name: 'Finland', code: 'FI', slug: 'finland' },
  'kirkkonummi':              { name: 'Finland', code: 'FI', slug: 'finland' },
  'kokkola':                  { name: 'Finland', code: 'FI', slug: 'finland' },
  'kotka':                    { name: 'Finland', code: 'FI', slug: 'finland' },
  'kouvola':                  { name: 'Finland', code: 'FI', slug: 'finland' },
  'kristiinankaupunki':       { name: 'Finland', code: 'FI', slug: 'finland' },
  'kuopio':                   { name: 'Finland', code: 'FI', slug: 'finland' },
  'lahti':                    { name: 'Finland', code: 'FI', slug: 'finland' },
  'lappeenranta':             { name: 'Finland', code: 'FI', slug: 'finland' },
  'lempäälä':                 { name: 'Finland', code: 'FI', slug: 'finland' },
  'lempala':                  { name: 'Finland', code: 'FI', slug: 'finland' },
  'lohja':                    { name: 'Finland', code: 'FI', slug: 'finland' },
  'mikkeli':                  { name: 'Finland', code: 'FI', slug: 'finland' },
  'mäntyharju':               { name: 'Finland', code: 'FI', slug: 'finland' },
  'nokia':                    { name: 'Finland', code: 'FI', slug: 'finland' },
  'nurmijärvi':               { name: 'Finland', code: 'FI', slug: 'finland' },
  'nurmijarvi':               { name: 'Finland', code: 'FI', slug: 'finland' },
  'oulu':                     { name: 'Finland', code: 'FI', slug: 'finland' },
  'pieksämäki':               { name: 'Finland', code: 'FI', slug: 'finland' },
  'pieksamaki':               { name: 'Finland', code: 'FI', slug: 'finland' },
  'pirkkala':                 { name: 'Finland', code: 'FI', slug: 'finland' },
  'pori':                     { name: 'Finland', code: 'FI', slug: 'finland' },
  'porvoo':                   { name: 'Finland', code: 'FI', slug: 'finland' },
  'raisio':                   { name: 'Finland', code: 'FI', slug: 'finland' },
  'rauma':                    { name: 'Finland', code: 'FI', slug: 'finland' },
  'riihimäki':                { name: 'Finland', code: 'FI', slug: 'finland' },
  'riihimaki':                { name: 'Finland', code: 'FI', slug: 'finland' },
  'rovaniemi':                { name: 'Finland', code: 'FI', slug: 'finland' },
  'salo':                     { name: 'Finland', code: 'FI', slug: 'finland' },
  'savonlinna':               { name: 'Finland', code: 'FI', slug: 'finland' },
  'seinäjoki':                { name: 'Finland', code: 'FI', slug: 'finland' },
  'seinajoki':                { name: 'Finland', code: 'FI', slug: 'finland' },
  'sipoo':                    { name: 'Finland', code: 'FI', slug: 'finland' },
  'tampere':                  { name: 'Finland', code: 'FI', slug: 'finland' },
  'tornio':                   { name: 'Finland', code: 'FI', slug: 'finland' },
  'turku':                    { name: 'Finland', code: 'FI', slug: 'finland' },
  'tuusula':                  { name: 'Finland', code: 'FI', slug: 'finland' },
  'vaasa':                    { name: 'Finland', code: 'FI', slug: 'finland' },
  'valkeakoski':              { name: 'Finland', code: 'FI', slug: 'finland' },
  'vantaa':                   { name: 'Finland', code: 'FI', slug: 'finland' },
  'varkaus':                  { name: 'Finland', code: 'FI', slug: 'finland' },
  'ylöjärvi':                 { name: 'Finland', code: 'FI', slug: 'finland' },
  'ylojarvi':                 { name: 'Finland', code: 'FI', slug: 'finland' },
  // ── Denmark ──────────────────────────────────────────────────────────────
  'aalborg':                  { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'aarhus':                   { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'branderup':                { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'christiansfeld':           { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'copenhagen':               { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'esbjerg':                  { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'glostrup':                 { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'holster':                  { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'ishøj':                    { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'ishoej':                   { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'københavn':                { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'kobenhavn':                { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'krusaa':                   { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'kruså':                    { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'odense':                   { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'taastrup':                 { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'tinglev':                  { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'slagelse':                 { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'vallensbæk':               { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'vejle':                    { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'viby':                     { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'videbæk':                  { name: 'Denmark', code: 'DK', slug: 'denmark' },
  'vojens':                   { name: 'Denmark', code: 'DK', slug: 'denmark' },
  // ── Germany ──────────────────────────────────────────────────────────────
  'augsburg':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'backnang':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'beimerstetten':            { name: 'Germany', code: 'DE', slug: 'germany' },
  'bäumenheim':               { name: 'Germany', code: 'DE', slug: 'germany' },
  'berlin':                   { name: 'Germany', code: 'DE', slug: 'germany' },
  'bielefeld':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'bochum':                   { name: 'Germany', code: 'DE', slug: 'germany' },
  'bonn':                     { name: 'Germany', code: 'DE', slug: 'germany' },
  'braunschweig':             { name: 'Germany', code: 'DE', slug: 'germany' },
  'brunswick':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'braunschweig/brunswick':   { name: 'Germany', code: 'DE', slug: 'germany' },
  'bremen':                   { name: 'Germany', code: 'DE', slug: 'germany' },
  'bückeburg':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'buckeburg':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'calden':                   { name: 'Germany', code: 'DE', slug: 'germany' },
  'celle':                    { name: 'Germany', code: 'DE', slug: 'germany' },
  'chemnitz':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'darmstadt':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'deggendorf':               { name: 'Germany', code: 'DE', slug: 'germany' },
  'dingolfing':               { name: 'Germany', code: 'DE', slug: 'germany' },
  'donauwörth':               { name: 'Germany', code: 'DE', slug: 'germany' },
  'dortmund':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'duisburg':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'dresden':                  { name: 'Germany', code: 'DE', slug: 'germany' },
  'düren':                    { name: 'Germany', code: 'DE', slug: 'germany' },
  'dusseldorf':               { name: 'Germany', code: 'DE', slug: 'germany' },
  'duesseldorf':              { name: 'Germany', code: 'DE', slug: 'germany' },
  'düsseldorf':               { name: 'Germany', code: 'DE', slug: 'germany' },
  'erfurt':                   { name: 'Germany', code: 'DE', slug: 'germany' },
  'erlangen':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'eschborn':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'ettlingen':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'faßberg':                  { name: 'Germany', code: 'DE', slug: 'germany' },
  'flöha':                    { name: 'Germany', code: 'DE', slug: 'germany' },
  'floeha':                   { name: 'Germany', code: 'DE', slug: 'germany' },
  'frankfurt':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'frankfurt am main':        { name: 'Germany', code: 'DE', slug: 'germany' },
  'fritzlar':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'halle':                    { name: 'Germany', code: 'DE', slug: 'germany' },
  'hamburg':                  { name: 'Germany', code: 'DE', slug: 'germany' },
  'hannover':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'hanover':                  { name: 'Germany', code: 'DE', slug: 'germany' },
  'hattingen':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'heidelberg':               { name: 'Germany', code: 'DE', slug: 'germany' },
  'herne':                    { name: 'Germany', code: 'DE', slug: 'germany' },
  'immenstaad am bodensee':   { name: 'Germany', code: 'DE', slug: 'germany' },
  'ingolstadt':               { name: 'Germany', code: 'DE', slug: 'germany' },
  'karlsruhe':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'kassel':                   { name: 'Germany', code: 'DE', slug: 'germany' },
  'kiel':                     { name: 'Germany', code: 'DE', slug: 'germany' },
  'koblenz':                  { name: 'Germany', code: 'DE', slug: 'germany' },
  'köln':                     { name: 'Germany', code: 'DE', slug: 'germany' },
  'koeln':                    { name: 'Germany', code: 'DE', slug: 'germany' },
  'koln':                     { name: 'Germany', code: 'DE', slug: 'germany' },
  'cologne':                  { name: 'Germany', code: 'DE', slug: 'germany' },
  'langenfeld':               { name: 'Germany', code: 'DE', slug: 'germany' },
  'laupheim':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'leipzig':                  { name: 'Germany', code: 'DE', slug: 'germany' },
  'ludwigsburg':              { name: 'Germany', code: 'DE', slug: 'germany' },
  'lübeck':                   { name: 'Germany', code: 'DE', slug: 'germany' },
  'mainz':                    { name: 'Germany', code: 'DE', slug: 'germany' },
  'manching':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'mannheim':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'münchen':                  { name: 'Germany', code: 'DE', slug: 'germany' },
  'muenchen':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'munich':                   { name: 'Germany', code: 'DE', slug: 'germany' },
  'niederstetten':            { name: 'Germany', code: 'DE', slug: 'germany' },
  'nordholz':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'nonnweiler':               { name: 'Germany', code: 'DE', slug: 'germany' },
  'nürnberg':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'nuernberg':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'nuremberg':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'nurnberg':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'offenbach':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'osnabrück':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'passau':                   { name: 'Germany', code: 'DE', slug: 'germany' },
  'plattling':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'pronsfeld':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'ratingen':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'regensburg':               { name: 'Germany', code: 'DE', slug: 'germany' },
  'remptendorf':              { name: 'Germany', code: 'DE', slug: 'germany' },
  'rosenheim':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'rostock':                  { name: 'Germany', code: 'DE', slug: 'germany' },
  'saarbrücken':              { name: 'Germany', code: 'DE', slug: 'germany' },
  'schenefeld':               { name: 'Germany', code: 'DE', slug: 'germany' },
  'solingen':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'stade':                    { name: 'Germany', code: 'DE', slug: 'germany' },
  'straubing':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'stuttgart':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'taufkirchen':              { name: 'Germany', code: 'DE', slug: 'germany' },
  'trier':                    { name: 'Germany', code: 'DE', slug: 'germany' },
  'ulm':                      { name: 'Germany', code: 'DE', slug: 'germany' },
  'westendorf':               { name: 'Germany', code: 'DE', slug: 'germany' },
  'wettenberg':               { name: 'Germany', code: 'DE', slug: 'germany' },
  'wetter':                   { name: 'Germany', code: 'DE', slug: 'germany' },
  'wiesbaden':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'wolfsburg':                { name: 'Germany', code: 'DE', slug: 'germany' },
  'wunstorf':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  'würzburg':                 { name: 'Germany', code: 'DE', slug: 'germany' },
  // ── Netherlands ──────────────────────────────────────────────────────────
  'aalten':                   { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'alkmaar':                  { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'almere':                   { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'alphen aan den rijn':      { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'amersfoort':               { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'amsterdam':                { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'apeldoorn':                { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'arnhem':                   { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'barneveld':                { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'bergen op zoom':           { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'best':                     { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'breda':                    { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'de lier':                  { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'den bosch':                { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'diemen':                   { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'doetinchem':               { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'dordrecht':                { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'dronten':                  { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'ede':                      { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'eindhoven':                { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'enschede':                 { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'etten-leur':               { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'groningen':                { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'den haag':                 { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'the hague':                { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'haarlem':                  { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'heemskerk':                { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'heerenveen':               { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'heerlen':                  { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'hengelo':                  { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'herkenbosch':              { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'hilversum':                { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'hoofddorp':                { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'den hoorn':                { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'huizen':                   { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'ijmuiden':                 { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'kampen':                   { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'leiden':                   { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'leeuwarden':               { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'lichtenvoorde':            { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'maastricht':               { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'meppel':                   { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'moerdijk':                 { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'nijmegen':                 { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'oss':                      { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'purmerend':                { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'rj nijkerk':               { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'roosendaal':               { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'rotterdam':                { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'sittard':                  { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'tholen':                   { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'tilburg':                  { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'utrecht':                  { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'veenendaal':               { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'venlo':                    { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'winterswijk':              { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'zundert':                  { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
  'zwolle':                   { name: 'Netherlands', code: 'NL', slug: 'netherlands' },
    // ── Norway ───────────────────────────────────────────────────────────────
  'bergen':                   { name: 'Norway', code: 'NO', slug: 'norway' },
  'fornebu':                  { name: 'Norway', code: 'NO', slug: 'norway' },
  'fredrikstad':              { name: 'Norway', code: 'NO', slug: 'norway' },
  'grimstad':                 { name: 'Norway', code: 'NO', slug: 'norway' },
  'hafrsfjord':               { name: 'Norway', code: 'NO', slug: 'norway' },
  'kristiansand':             { name: 'Norway', code: 'NO', slug: 'norway' },
  'oslo':                     { name: 'Norway', code: 'NO', slug: 'norway' },
  'sandefjord':               { name: 'Norway', code: 'NO', slug: 'norway' },
  'sarpsborg':                { name: 'Norway', code: 'NO', slug: 'norway' },
  'stavanger':                { name: 'Norway', code: 'NO', slug: 'norway' },
  'strommen':                 { name: 'Norway', code: 'NO', slug: 'norway' },
  'strømmen':                 { name: 'Norway', code: 'NO', slug: 'norway' },
  'tromsø':                   { name: 'Norway', code: 'NO', slug: 'norway' },
  'tromso':                   { name: 'Norway', code: 'NO', slug: 'norway' },
  'trondheim':                { name: 'Norway', code: 'NO', slug: 'norway' },
  // ── Sweden ───────────────────────────────────────────────────────────────
  'bollnäs':                  { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'borlänge':                 { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'borås':                    { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'boras':                    { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'bro':                      { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'enkoping':                 { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'enköping':                 { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'eskilstuna':               { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'falkenberg':               { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'falun':                    { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'fors':                     { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'gothenburg':               { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'goteborg':                 { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'göteborg':                 { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'goetene':                  { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'götene':                   { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'gävle':                    { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'gavle':                    { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'halmstad':                 { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'helsingborg':              { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'jönköping':                { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'jonkoping':                { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'kalix':                    { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'kalmar':                   { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'karlstad':                 { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'kiruna':                   { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'kista':                    { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'linköping':                { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'linkoping':                { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'ljusdal':                  { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'lulea':                    { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'luleå':                    { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'lund':                     { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'malmö':                    { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'malmo':                    { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'mölndal':                  { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'norrköping':               { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'norrkoping':               { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'nykoping':                 { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'nyköping':                 { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'örebro':                   { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'orebro':                   { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'sala':                     { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'skelleftea':               { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'skellefteå':               { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'skillingaryd':             { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'skoghall':                 { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'solna':                    { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'sth solna':                { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'stockholm':                { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'sundsvall':                { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'torsby':                   { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'umeå':                     { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'umea':                     { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'uppsala':                  { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'västerås':                 { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'vasteras':                 { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'vaesteras':                { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'växjö':                    { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'älmhult':                  { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'örnsköldsvik':             { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'ostersund':                { name: 'Sweden', code: 'SE', slug: 'sweden' },
  'östersund':                { name: 'Sweden', code: 'SE', slug: 'sweden' },
  // ── Baltics ──────────────────────────────────────────────────────────────
  'rīga':                     { name: 'Latvia', code: 'LV', slug: 'latvia' },
  'riga':                     { name: 'Latvia', code: 'LV', slug: 'latvia' },
  'pärnu':                    { name: 'Estonia', code: 'EE', slug: 'estonia' },
  'tallinn':                  { name: 'Estonia', code: 'EE', slug: 'estonia' },
  'tartu':                    { name: 'Estonia', code: 'EE', slug: 'estonia' },
  'vilnius':                  { name: 'Lithuania', code: 'LT', slug: 'lithuania' },
  'kaunas':                   { name: 'Lithuania', code: 'LT', slug: 'lithuania' },
   
  // ── Austria ──────────────────────────────────────────────────────────────
  'graz':                     { name: 'Austria', code: 'AT', slug: 'austria' },
  'innsbruck':                { name: 'Austria', code: 'AT', slug: 'austria' },
  'linz':                     { name: 'Austria', code: 'AT', slug: 'austria' },
  'parndorf':                 { name: 'Austria', code: 'AT', slug: 'austria' },
  'poggersdorf':              { name: 'Austria', code: 'AT', slug: 'austria' },
  'salzburg':                 { name: 'Austria', code: 'AT', slug: 'austria' },
  'wien':                     { name: 'Austria', code: 'AT', slug: 'austria' },
  'vienna':                   { name: 'Austria', code: 'AT', slug: 'austria' },
  // ── Belgium ──────────────────────────────────────────────────────────────
  'antwerp':                  { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'antwerpen':                { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'brussels':                 { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'bruxelles':                { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'brussel':                  { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'gosselies':                { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'herstal':                  { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'kontich':                  { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'leuven':                   { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'loppem':                   { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'lummen':                   { name: 'Belgium', code: 'BE', slug: 'belgium' },
  'machelen':                 { name: 'Belgium', code: 'BE', slug: 'belgium' },
  // ── Czech Republic ───────────────────────────────────────────────────────
  'brno':                     { name: 'Czech Republic', code: 'CZ', slug: 'czech-republic' },
  'ostrava':                  { name: 'Czech Republic', code: 'CZ', slug: 'czech-republic' },
  'prague':                   { name: 'Czech Republic', code: 'CZ', slug: 'czech-republic' },
  'praha':                    { name: 'Czech Republic', code: 'CZ', slug: 'czech-republic' },
  'usti nad labem':           { name: 'Czech Republic', code: 'CZ', slug: 'czech-republic' },
  // ── France ───────────────────────────────────────────────────────────────
  'alissas':                  { name: 'France', code: 'FR', slug: 'france' },
  'amiens':                   { name: 'France', code: 'FR', slug: 'france' },
  'annecy':                   { name: 'France', code: 'FR', slug: 'france' },
  'asnières sur seine':       { name: 'France', code: 'FR', slug: 'france' },
  'auch':                     { name: 'France', code: 'FR', slug: 'france' },
  'bordeaux':                 { name: 'France', code: 'FR', slug: 'france' },
  'bouc bel ai':              { name: 'France', code: 'FR', slug: 'france' },
  'bourges':                  { name: 'France', code: 'FR', slug: 'france' },
  'brest':                    { name: 'France', code: 'FR', slug: 'france' },
  'cesson-sevigné':           { name: 'France', code: 'FR', slug: 'france' },
  'colombes':                 { name: 'France', code: 'FR', slug: 'france' },
  'eguilles':                 { name: 'France', code: 'FR', slug: 'france' },
  'frejus':                   { name: 'France', code: 'FR', slug: 'france' },
  'geispolsheim':             { name: 'France', code: 'FR', slug: 'france' },
  'grenoble':                 { name: 'France', code: 'FR', slug: 'france' },
  'guipavas':                 { name: 'France', code: 'FR', slug: 'france' },
  'la chapel saint aubin':    { name: 'France', code: 'FR', slug: 'france' },
  'la rochelle':              { name: 'France', code: 'FR', slug: 'france' },
  'la roche-sur-yon':         { name: 'France', code: 'FR', slug: 'france' },
  'les pennes mirabeau':      { name: 'France', code: 'FR', slug: 'france' },
  'les sorinières':           { name: 'France', code: 'FR', slug: 'france' },
  'lille':                    { name: 'France', code: 'FR', slug: 'france' },
  'lyon':                     { name: 'France', code: 'FR', slug: 'france' },
  'marseille':                { name: 'France', code: 'FR', slug: 'france' },
  'merignac':                 { name: 'France', code: 'FR', slug: 'france' },
  'metz':                     { name: 'France', code: 'FR', slug: 'france' },
  'montpellier':              { name: 'France', code: 'FR', slug: 'france' },
  'nancy':                    { name: 'France', code: 'FR', slug: 'france' },
  'nantes':                   { name: 'France', code: 'FR', slug: 'france' },
  'narbonne':                 { name: 'France', code: 'FR', slug: 'france' },
  'nice':                     { name: 'France', code: 'FR', slug: 'france' },
  'noicy le sec':             { name: 'France', code: 'FR', slug: 'france' },
  'noyarey':                  { name: 'France', code: 'FR', slug: 'france' },
  'olemps':                   { name: 'France', code: 'FR', slug: 'france' },
  'ormes':                    { name: 'France', code: 'FR', slug: 'france' },
  'paris':                    { name: 'France', code: 'FR', slug: 'france' },
  'pau':                      { name: 'France', code: 'FR', slug: 'france' },
  'quimper':                  { name: 'France', code: 'FR', slug: 'france' },
  'rennes':                   { name: 'France', code: 'FR', slug: 'france' },
  'rochefort':                { name: 'France', code: 'FR', slug: 'france' },
  'rouen':                    { name: 'France', code: 'FR', slug: 'france' },
  'sainghin-en-mélantois':    { name: 'France', code: 'FR', slug: 'france' },
  'saint-genis-pouilly':      { name: 'France', code: 'FR', slug: 'france' },
  'saint lô':                 { name: 'France', code: 'FR', slug: 'france' },
  'saint priest':             { name: 'France', code: 'FR', slug: 'france' },
  'saint-nazaire':            { name: 'France', code: 'FR', slug: 'france' },
  'six fours':                { name: 'France', code: 'FR', slug: 'france' },
  'sotteville-lès-rouen':     { name: 'France', code: 'FR', slug: 'france' },
  'st laurent du var':        { name: 'France', code: 'FR', slug: 'france' },
  'strasbourg':               { name: 'France', code: 'FR', slug: 'france' },
  'toulouse':                 { name: 'France', code: 'FR', slug: 'france' },
  'tours':                    { name: 'France', code: 'FR', slug: 'france' },
  'trappes':                  { name: 'France', code: 'FR', slug: 'france' },
  'ussac':                    { name: 'France', code: 'FR', slug: 'france' },
  'vallauris':                { name: 'France', code: 'FR', slug: 'france' },
  'velaux':                   { name: 'France', code: 'FR', slug: 'france' },
  'verneuil en halatte':      { name: 'France', code: 'FR', slug: 'france' },
  'wasquehal':                { name: 'France', code: 'FR', slug: 'france' },
  // ── Hungary ──────────────────────────────────────────────────────────────
  'budapest':                 { name: 'Hungary', code: 'HU', slug: 'hungary' },
  // ── Ireland ──────────────────────────────────────────────────────────────
  'cork':                     { name: 'Ireland', code: 'IE', slug: 'ireland' },
  'dublin':                   { name: 'Ireland', code: 'IE', slug: 'ireland' },
  // Italy
  'ferrara':                  { name: 'Italy', code: 'IT', slug: 'italy' },
  'melfi':                    { name: 'Italy', code: 'IT', slug: 'italy' },
  'milan':                    { name: 'Italy', code: 'IT', slug: 'italy' },
  'milano':                   { name: 'Italy', code: 'IT', slug: 'italy' },
  'naples':                   { name: 'Italy', code: 'IT', slug: 'italy' },
  'napoli':                   { name: 'Italy', code: 'IT', slug: 'italy' },
  'nogarole rocca':           { name: 'Italy', code: 'IT', slug: 'italy' },
  'padova':                   { name: 'Italy', code: 'IT', slug: 'italy' },
  'pero':                     { name: 'Italy', code: 'IT', slug: 'italy' },
  'roma':                     { name: 'Italy', code: 'IT', slug: 'italy' },
  'rome':                     { name: 'Italy', code: 'IT', slug: 'italy' },
  'sassari':                  { name: 'Italy', code: 'IT', slug: 'italy' },
  'taranto':                  { name: 'Italy', code: 'IT', slug: 'italy' },
  'torino':                   { name: 'Italy', code: 'IT', slug: 'italy' },
  'turin':                    { name: 'Italy', code: 'IT', slug: 'italy' },
  'verona':                   { name: 'Italy', code: 'IT', slug: 'italy' },
  // ── North Macedonia ──────────────────────────────────────────────────────
  'skopje':                   { name: 'North Macedonia', code: 'MK', slug: 'north-macedonia' },
  // ── Poland ───────────────────────────────────────────────────────────────
  'bydgoszcz':                { name: 'Poland', code: 'PL', slug: 'poland' },
  'gardno':                   { name: 'Poland', code: 'PL', slug: 'poland' },
  'gdańsk':                   { name: 'Poland', code: 'PL', slug: 'poland' },
  'gdansk':                   { name: 'Poland', code: 'PL', slug: 'poland' },
  'gdynia':                   { name: 'Poland', code: 'PL', slug: 'poland' },
  'gluchow':                  { name: 'Poland', code: 'PL', slug: 'poland' },
  'kalisz':                   { name: 'Poland', code: 'PL', slug: 'poland' },
  'kraków':                   { name: 'Poland', code: 'PL', slug: 'poland' },
  'katowice':                 { name: 'Poland', code: 'PL', slug: 'poland' },
  'krakow':                   { name: 'Poland', code: 'PL', slug: 'poland' },
  'łódź':                     { name: 'Poland', code: 'PL', slug: 'poland' },
  'lodz':                     { name: 'Poland', code: 'PL', slug: 'poland' },
  'lublin':                   { name: 'Poland', code: 'PL', slug: 'poland' },
  'ostrołęka':                { name: 'Poland', code: 'PL', slug: 'poland' },
  'piaseczno':                { name: 'Poland', code: 'PL', slug: 'poland' },
  'poznań':                   { name: 'Poland', code: 'PL', slug: 'poland' },
  'poznan':                   { name: 'Poland', code: 'PL', slug: 'poland' },
  'radom':                    { name: 'Poland', code: 'PL', slug: 'poland' },
  'tychy':                    { name: 'Poland', code: 'PL', slug: 'poland' },
  'warsaw':                   { name: 'Poland', code: 'PL', slug: 'poland' },
  'warszawa':                 { name: 'Poland', code: 'PL', slug: 'poland' },
  'województwo':              { name: 'Poland', code: 'PL', slug: 'poland' },
  'wrocław':                  { name: 'Poland', code: 'PL', slug: 'poland' },
  'wroclaw':                  { name: 'Poland', code: 'PL', slug: 'poland' },
  // ── Portugal ─────────────────────────────────────────────────────────────
  'lisbon':                   { name: 'Portugal', code: 'PT', slug: 'portugal' },
  'lisboa':                   { name: 'Portugal', code: 'PT', slug: 'portugal' },
  'porto':                    { name: 'Portugal', code: 'PT', slug: 'portugal' },
  // ── Romania ──────────────────────────────────────────────────────────────
  'bucurești':                { name: 'Romania', code: 'RO', slug: 'romania' },
  'bucharest':                { name: 'Romania', code: 'RO', slug: 'romania' },
  'cluj':                     { name: 'Romania', code: 'RO', slug: 'romania' },
  'cluj-napoca':              { name: 'Romania', code: 'RO', slug: 'romania' },
   // Slovakia
  'bratislava':               { name: 'Slovakia', code: 'SK', slug: 'slovakia' },
  'kosice':                   { name: 'Slovakia', code: 'SK', slug: 'slovakia' },
  // ── Spain ────────────────────────────────────────────────────────────────
  'alicante':                 { name: 'Spain', code: 'ES', slug: 'spain' },
  'barcelona':                { name: 'Spain', code: 'ES', slug: 'spain' },
  'bilbao':                   { name: 'Spain', code: 'ES', slug: 'spain' },
  'getafe':                   { name: 'Spain', code: 'ES', slug: 'spain' },
  'gijon':                    { name: 'Spain', code: 'ES', slug: 'spain' },
  'granada':                  { name: 'Spain', code: 'ES', slug: 'spain' },
  'leon':                     { name: 'Spain', code: 'ES', slug: 'spain' },
  'lleida':                   { name: 'Spain', code: 'ES', slug: 'spain' },
  'madrid':                   { name: 'Spain', code: 'ES', slug: 'spain' },
  'málaga':                   { name: 'Spain', code: 'ES', slug: 'spain' },
  'malaga':                   { name: 'Spain', code: 'ES', slug: 'spain' },
  'murcia':                   { name: 'Spain', code: 'ES', slug: 'spain' },
  'san fernando':             { name: 'Spain', code: 'ES', slug: 'spain' },
  'santander':                { name: 'Spain', code: 'ES', slug: 'spain' },
  'sevilla':                  { name: 'Spain', code: 'ES', slug: 'spain' },
  'seville':                  { name: 'Spain', code: 'ES', slug: 'spain' },
  'tarragona':                { name: 'Spain', code: 'ES', slug: 'spain' },
  'valencia':                 { name: 'Spain', code: 'ES', slug: 'spain' },
  'valladolid':               { name: 'Spain', code: 'ES', slug: 'spain' },
  // ── Switzerland ──────────────────────────────────────────────────────────
  'basel':                    { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  'bern':                     { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  'brüttisellen':             { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  'genève':                   { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  'geneve':                   { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  'geneva':                   { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  'lausenne':                 { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  'sion':                     { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  'zürich':                   { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  'zurich':                   { name: 'Switzerland', code: 'CH', slug: 'switzerland' },
  // Turkey ───────────────────────────────────────────────────────
  'ankara':                   { name: 'Turkey', code: 'TR', slug: 'turkey' },
  'istanbul merkez':          { name: 'Turkey', code: 'TR', slug: 'turkey' },
  'istanbul sisli':           { name: 'Turkey', code: 'TR', slug: 'turkey' },
  'izmir':                    { name: 'Turkey', code: 'TR', slug: 'turkey' },
  'samsun':                   { name: 'Turkey', code: 'TR', slug: 'turkey' },
  // ── United Kingdom ───────────────────────────────────────────────────────
  'aberdeen':                 { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'armagh':                   { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'ballymoney':               { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'basingstoke':              { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'barlaston':                { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'belfast':                  { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'birmingham':               { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'bristol':                  { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'cambridge':                { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'cardiff':                  { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'derry':                    { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'doncaster':                { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'dundee':                   { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'edinburgh':                { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'gateshead':                { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'glasgow':                  { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'hull':                     { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'keighley':                 { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'leeds':                    { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'leicester':                { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'liverpool':                { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'london':                   { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'manchester':               { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'middlesbrough':            { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'newport':                  { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'newry':                    { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'northampton':              { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'norwich':                  { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'nottingham':               { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'oxford':                   { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'peterborough':             { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'plymouth':                 { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'portadown':                { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'reading':                  { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'sheffield':                { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'sidcup london':            { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'slough':                   { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'southampton':              { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'stevenage':                { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'warrington':               { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'woking':                   { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },
  'yorkshire':                { name: 'United Kingdom', code: 'GB', slug: 'united-kingdom' },

  // ── United States (states) ───────────────────────────────────────────────
  // COUNTRY_MAP takes priority for 'georgia' (country Georgia/GE), so adding it here is safe.
  'alabama':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'alaska':                   { name: 'United States', code: 'US', slug: 'united-states' },
  'arizona':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'arkansas':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'california':               { name: 'United States', code: 'US', slug: 'united-states' },
  'colorado':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'connecticut':              { name: 'United States', code: 'US', slug: 'united-states' },
  'delaware':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'florida':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'georgia':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'hawaii':                   { name: 'United States', code: 'US', slug: 'united-states' },
  'idaho':                    { name: 'United States', code: 'US', slug: 'united-states' },
  'illinois':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'indiana':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'iowa':                     { name: 'United States', code: 'US', slug: 'united-states' },
  'kansas':                   { name: 'United States', code: 'US', slug: 'united-states' },
  'kentucky':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'louisiana':                { name: 'United States', code: 'US', slug: 'united-states' },
  'maine':                    { name: 'United States', code: 'US', slug: 'united-states' },
  'maryland':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'massachusetts':            { name: 'United States', code: 'US', slug: 'united-states' },
  'michigan':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'minnesota':                { name: 'United States', code: 'US', slug: 'united-states' },
  'mississippi':              { name: 'United States', code: 'US', slug: 'united-states' },
  'missouri':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'montana':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'nebraska':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'nevada':                   { name: 'United States', code: 'US', slug: 'united-states' },
  'new hampshire':            { name: 'United States', code: 'US', slug: 'united-states' },
  'new jersey':               { name: 'United States', code: 'US', slug: 'united-states' },
  'new mexico':               { name: 'United States', code: 'US', slug: 'united-states' },
  'new york':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'north carolina':           { name: 'United States', code: 'US', slug: 'united-states' },
  'north dakota':             { name: 'United States', code: 'US', slug: 'united-states' },
  'ohio':                     { name: 'United States', code: 'US', slug: 'united-states' },
  'oklahoma':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'oregon':                   { name: 'United States', code: 'US', slug: 'united-states' },
  'pennsylvania':             { name: 'United States', code: 'US', slug: 'united-states' },
  'rhode island':             { name: 'United States', code: 'US', slug: 'united-states' },
  'south carolina':           { name: 'United States', code: 'US', slug: 'united-states' },
  'south dakota':             { name: 'United States', code: 'US', slug: 'united-states' },
  'tennessee':                { name: 'United States', code: 'US', slug: 'united-states' },
  'texas':                    { name: 'United States', code: 'US', slug: 'united-states' },
  'utah':                     { name: 'United States', code: 'US', slug: 'united-states' },
  'vermont':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'virginia':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'washington':               { name: 'United States', code: 'US', slug: 'united-states' },
  'west virginia':            { name: 'United States', code: 'US', slug: 'united-states' },
  'wisconsin':                { name: 'United States', code: 'US', slug: 'united-states' },
  'wyoming':                  { name: 'United States', code: 'US', slug: 'united-states' },
  // ── United States (major cities) ─────────────────────────────────────────
  'allen':                    { name: 'United States', code: 'US', slug: 'united-states' },
  'atlanta':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'austin':                   { name: 'United States', code: 'US', slug: 'united-states' },
  'baltimore':                { name: 'United States', code: 'US', slug: 'united-states' },
  'boston':                   { name: 'United States', code: 'US', slug: 'united-states' },
  'charlotte':                { name: 'United States', code: 'US', slug: 'united-states' },
  'chicago':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'cleveland':                { name: 'United States', code: 'US', slug: 'united-states' },
  'coal valley':              { name: 'United States', code: 'US', slug: 'united-states' },
  'dallas':                   { name: 'United States', code: 'US', slug: 'united-states' },
  'davie':                    { name: 'United States', code: 'US', slug: 'united-states' },
  'denver':                   { name: 'United States', code: 'US', slug: 'united-states' },
  'detroit':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'grand rapids':             { name: 'United States', code: 'US', slug: 'united-states' },
  'harrisburg':               { name: 'United States', code: 'US', slug: 'united-states' },
  'houston':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'indianapolis':             { name: 'United States', code: 'US', slug: 'united-states' },
  'kansas city':              { name: 'United States', code: 'US', slug: 'united-states' },
  'las vegas':                { name: 'United States', code: 'US', slug: 'united-states' },
  'los angeles':              { name: 'United States', code: 'US', slug: 'united-states' },
  'madison':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'markham':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'memphis':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'miami':                    { name: 'United States', code: 'US', slug: 'united-states' },
  'minneapolis':              { name: 'United States', code: 'US', slug: 'united-states' },
  'miramar':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'moline':                   { name: 'United States', code: 'US', slug: 'united-states' },
  'nashville':                { name: 'United States', code: 'US', slug: 'united-states' },
  'new york city':            { name: 'United States', code: 'US', slug: 'united-states' },
  'nyc':                      { name: 'United States', code: 'US', slug: 'united-states' },
  'orlando':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'philadelphia':             { name: 'United States', code: 'US', slug: 'united-states' },
  'phoenix':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'portland':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'raleigh':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'richmond':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'san diego':                { name: 'United States', code: 'US', slug: 'united-states' },
  'san francisco':            { name: 'United States', code: 'US', slug: 'united-states' },
  'san jose':                 { name: 'United States', code: 'US', slug: 'united-states' },
  'seattle':                  { name: 'United States', code: 'US', slug: 'united-states' },
  'springfield':              { name: 'United States', code: 'US', slug: 'united-states' },
  'tulsa':                    { name: 'United States', code: 'US', slug: 'united-states' },
  'washington DC':            { name: 'United States', code: 'US', slug: 'united-states' },
  // ── Canada (provinces) ───────────────────────────────────────────────────
  'alberta':                  { name: 'Canada', code: 'CA', slug: 'canada' },
  'british columbia':         { name: 'Canada', code: 'CA', slug: 'canada' },
  'manitoba':                 { name: 'Canada', code: 'CA', slug: 'canada' },
  'new brunswick':            { name: 'Canada', code: 'CA', slug: 'canada' },
  'newfoundland':             { name: 'Canada', code: 'CA', slug: 'canada' },
  'nova scotia':              { name: 'Canada', code: 'CA', slug: 'canada' },
  'ontario':                  { name: 'Canada', code: 'CA', slug: 'canada' },
  'prince edward island':     { name: 'Canada', code: 'CA', slug: 'canada' },
  'quebec':                   { name: 'Canada', code: 'CA', slug: 'canada' },
  'québec':                   { name: 'Canada', code: 'CA', slug: 'canada' },
  'saskatchewan':             { name: 'Canada', code: 'CA', slug: 'canada' },
  // ── Canada (major cities) ─────────────────────────────────────────────────
  'calgary':                  { name: 'Canada', code: 'CA', slug: 'canada' },
  'delta':                    { name: 'Canada', code: 'CA', slug: 'canada' },
  'edmonton':                 { name: 'Canada', code: 'CA', slug: 'canada' },
  'montreal':                 { name: 'Canada', code: 'CA', slug: 'canada' },
  'montréal':                 { name: 'Canada', code: 'CA', slug: 'canada' },
  'ottawa':                   { name: 'Canada', code: 'CA', slug: 'canada' },
  'quebec city':              { name: 'Canada', code: 'CA', slug: 'canada' },
  'saint laurent':            { name: 'Canada', code: 'CA', slug: 'canada' },
  'toronto':                  { name: 'Canada', code: 'CA', slug: 'canada' },
  'vancouver':                { name: 'Canada', code: 'CA', slug: 'canada' },
  'winnipeg':                 { name: 'Canada', code: 'CA', slug: 'canada' },
  // Mexico
  'acapulco':                 { name: 'Mexico', code: 'MX', slug: 'mexico' },
  'cancun':                   { name: 'Mexico', code: 'MX', slug: 'mexico' },
  'coahuila':                 { name: 'Mexico', code: 'MX', slug: 'mexico' },
  'guadalajara':              { name: 'Mexico', code: 'MX', slug: 'mexico' },
  'mexico city':              { name: 'Mexico', code: 'MX', slug: 'mexico' },
  'monterrey':                { name: 'Mexico', code: 'MX', slug: 'mexico' },
  'puebla':                   { name: 'Mexico', code: 'MX', slug: 'mexico' },
  // ── Central America ──────────────────────────────────────────────────────
  'belize city':              { name: 'Belize', code: 'BZ', slug: 'belize' },
  'san josé':                 { name: 'Costa Rica', code: 'CR', slug: 'costa-rica' },
  'san salvador':             { name: 'El Salvador', code: 'SV', slug: 'el-salvador' },
  'guatemala city':           { name: 'Guatemala', code: 'GT', slug: 'guatemala' },
  'ciudad de guatemala':      { name: 'Guatemala', code: 'GT', slug: 'guatemala' },
  'tegucigalpa':              { name: 'Honduras', code: 'HN', slug: 'honduras' },
  'managua':                  { name: 'Nicaragua', code: 'NI', slug: 'nicaragua' },
  'panama city':              { name: 'Panama', code: 'PA', slug: 'panama' },
  'ciudad de panamá':         { name: 'Panama', code: 'PA', slug: 'panama' },
  // ── South America ────────────────────────────────────────────────────────
  'buenos aires':             { name: 'Argentina', code: 'AR', slug: 'argentina' },
  'la paz':                   { name: 'Bolivia', code: 'BO', slug: 'bolivia' },
  'sucre':                    { name: 'Bolivia', code: 'BO', slug: 'bolivia' },
  'brasília':                 { name: 'Brazil', code: 'BR', slug: 'brazil' },
  'brasilia':                 { name: 'Brazil', code: 'BR', slug: 'brazil' },
  'rio de janeiro':           { name: 'Brazil', code: 'BR', slug: 'brazil' },
  'são paulo':                { name: 'Brazil', code: 'BR', slug: 'brazil' },
  'sao paulo':                { name: 'Brazil', code: 'BR', slug: 'brazil' },
  'santiago':                 { name: 'Chile', code: 'CL', slug: 'chile' },
  'bogotá':                   { name: 'Colombia', code: 'CO', slug: 'colombia' },
  'bogota':                   { name: 'Colombia', code: 'CO', slug: 'colombia' },
  'quito':                    { name: 'Ecuador', code: 'EC', slug: 'ecuador' },
  'asunción':                 { name: 'Paraguay', code: 'PY', slug: 'paraguay' },
  'asuncion':                 { name: 'Paraguay', code: 'PY', slug: 'paraguay' },
  'lima':                     { name: 'Peru', code: 'PE', slug: 'peru' },
  'paramaribo':               { name: 'Suriname', code: 'SR', slug: 'suriname' },
  'montevideo':               { name: 'Uruguay', code: 'UY', slug: 'uruguay' },
  'caracas':                  { name: 'Venezuela', code: 'VE', slug: 'venezuela' },
  // ── India ────────────────────────────────────────────────────────────────
  'ahmedabad':                { name: 'India', code: 'IN', slug: 'india' },
  'bengaluru':                { name: 'India', code: 'IN', slug: 'india' },
  'bangalore':                { name: 'India', code: 'IN', slug: 'india' },
  'bhubaneswar':              { name: 'India', code: 'IN', slug: 'india' },
  'calicut':                  { name: 'India', code: 'IN', slug: 'india' },
  'chandigarh':               { name: 'India', code: 'IN', slug: 'india' },
  'chennai':                  { name: 'India', code: 'IN', slug: 'india' },
  'coimbatore':               { name: 'India', code: 'IN', slug: 'india' },
  'delhi':                    { name: 'India', code: 'IN', slug: 'india' },
  'new delhi':                { name: 'India', code: 'IN', slug: 'india' },
  'ernakulam':                { name: 'India', code: 'IN', slug: 'india' },
  'gurgaon':                  { name: 'India', code: 'IN', slug: 'india' },
  'gurugram':                 { name: 'India', code: 'IN', slug: 'india' },
  'hyderabad':                { name: 'India', code: 'IN', slug: 'india' },
  'indore':                   { name: 'India', code: 'IN', slug: 'india' },
  'jaipur':                   { name: 'India', code: 'IN', slug: 'india' },
  'kochi':                    { name: 'India', code: 'IN', slug: 'india' },
  'kolkata':                  { name: 'India', code: 'IN', slug: 'india' },
  'lucknow':                  { name: 'India', code: 'IN', slug: 'india' },
  'mumbai':                   { name: 'India', code: 'IN', slug: 'india' },
  'nagpur':                   { name: 'India', code: 'IN', slug: 'india' },
  'noida':                    { name: 'India', code: 'IN', slug: 'india' },
  'pune':                     { name: 'India', code: 'IN', slug: 'india' },
  'surat':                    { name: 'India', code: 'IN', slug: 'india' },
  'vadodara':                 { name: 'India', code: 'IN', slug: 'india' },
  'vijayawada':               { name: 'India', code: 'IN', slug: 'india' },
  'visakhapatnam':            { name: 'India', code: 'IN', slug: 'india' },
  'vizag':                    { name: 'India', code: 'IN', slug: 'india' },
  // China  ─────────────────────────────────────────────────────────────
  'hangzhou':                 { name: 'China', code: 'CN', slug: 'china' },
  'hubei':                    { name: 'China', code: 'CN', slug: 'china' },
  'huzhou':                   { name: 'China', code: 'CN', slug: 'china' },
  'jiangxi':                  { name: 'China', code: 'CN', slug: 'china' },
  'jinan':                    { name: 'China', code: 'CN', slug: 'china' },
  'kunming':                  { name: 'China', code: 'CN', slug: 'china' },
  'kunshan':                  { name: 'China', code: 'CN', slug: 'china' },
  'nanchang':                 { name: 'China', code: 'CN', slug: 'china' },
  'nanjing':                  { name: 'China', code: 'CN', slug: 'china' },
  'nanxun':                   { name: 'China', code: 'CN', slug: 'china' },
  'ningbo':                   { name: 'China', code: 'CN', slug: 'china' },
  'sanya':                    { name: 'China', code: 'CN', slug: 'china' },
  'shaanxi':                  { name: 'China', code: 'CN', slug: 'china' },
  'shanghai':                 { name: 'China', code: 'CN', slug: 'china' },
  'shanxi':                   { name: 'China', code: 'CN', slug: 'china' },
  'shao xing':                { name: 'China', code: 'CN', slug: 'china' },
  'shenyang':                 { name: 'China', code: 'CN', slug: 'china' },
  'shenzhen':                 { name: 'China', code: 'CN', slug: 'china' },
  'sichuan':                  { name: 'China', code: 'CN', slug: 'china' },
  'taiyuan':                  { name: 'China', code: 'CN', slug: 'china' },
  'tianjin':                  { name: 'China', code: 'CN', slug: 'china' },
  'wuhan':                    { name: 'China', code: 'CN', slug: 'china' },
  'zhuhai':                   { name: 'China', code: 'CN', slug: 'china' },
   // Japan  ───────────────────────────────────────────────────────────────
  'osaka':                    { name: 'Japan', code: 'JP', slug: 'japan' },
  'tokyo':                    { name: 'Japan', code: 'JP', slug: 'japan' },
  // Southeast Asia  ─────────────────────────────────────────────────────────────
  'bangkok':                  { name: 'Thailand', code: 'TH', slug: 'thailand' },
  'daerah khusus ibukota jakarta': { name: 'Indonesia', code: 'ID', slug: 'indonesia' },
  'jakarta':                  { name: 'Indonesia', code: 'ID', slug: 'indonesia' },
  'ho chi minh city':         { name: 'Vietnam', code: 'VN', slug: 'vietnam' },
  'makati city':              { name: 'Philippines', code: 'PH', slug: 'philippines' },
  'manila':                   { name: 'Philippines', code: 'PH', slug: 'philippines' },
  'petaling jaya':            { name: 'Malaysia', code: 'MY', slug: 'malaysia' },
  'singapore':                { name: 'Singapore', code: 'SG', slug: 'singapore' },
  'taipei':                   { name: 'Taiwan', code: 'TW' , slug: 'taiwan' },
  // Saudi Arabia  ───────────────────────────────────────────────────────────────────
  'jeddah':                   { name: 'Saudi Arabia', code: 'SA', slug: 'saudi-arabia' },
  'makkah':                   { name: 'Saudi Arabia', code: 'SA', slug: 'saudi-arabia' },
  'riyadh':                   { name: 'Saudi Arabia', code: 'SA', slug: 'saudi-arabia' },
  // United Arab Emirates  ─────────────────────────────────────────────────────────────
  'abu dhabi':                { name: 'United Arab Emirates', code: 'AE', slug: 'united-arab-emirates' },
  'dubai':                    { name: 'United Arab Emirates', code: 'AE', slug: 'united-arab-emirates' },
  'sharjah':                  { name: 'United Arab Emirates', code: 'AE', slug: 'united-arab-emirates' },
  // Qatar  ────────────────────────────────────────────────────────────────────
  'doha':                     { name: 'Qatar', code: 'QA', slug: 'qatar' },
  // Australia  ────────────────────────────────────────────────────────────────
  'brisbane':                 { name: 'Australia', code: 'AU', slug: 'australia' },
  'canberra':                 { name: 'Australia', code: 'AU', slug: 'australia' },
  'gold coast':               { name: 'Australia', code: 'AU', slug: 'australia' },
  'mascot':                   { name: 'Australia', code: 'AU', slug: 'australia' },
  'melbourne':                { name: 'Australia', code: 'AU', slug: 'australia' },
  'newcastle':                { name: 'Australia', code: 'AU', slug: 'australia' },
  'perth':                    { name: 'Australia', code: 'AU', slug: 'australia' },
  'sydney':                   { name: 'Australia', code: 'AU', slug: 'australia' },

  // Capitals  ───────────────────────────────────────────────────────────────────
  'andorra la vella':         { name: 'Andorra', code: 'AD', slug: 'andorra' },
  'belgrade':                 { name: 'Serbia', code: 'RS', slug: 'serbia' },
  'cairo':                    { name: 'Egypt', code: 'EG', slug: 'egypt' },
  'ljubljana':                { name: 'Slovenia', code: 'SI', slug: 'slovenia' },
  'nairobi':                  { name: 'Kenya', code: 'KE', slug: 'kenya' },
  'zagreb':                   { name: 'Croatia', code: 'HR', slug: 'croatia' },
};

// Companies that only operate in one country — keyed by a substring of their career page URL.
// When location lookup fails for a job from one of these companies, fall back to this count
// instead of skipping the job.
const COMPANY_COUNTRY_FALLBACKS: Array<{ urlSubstring: string; country: CountryInfo }> = [
  { urlSubstring: 'academicwork.fi', country: { name: 'Finland', code: 'FI', slug: 'finland' } },
  { urlSubstring: 'sok.wd', country: { name: 'Finland', code: 'FI', slug: 'finland' } },
  { urlSubstring: 'upcloud.teamtailor.com', country: { name: 'Finland', code: 'FI', slug: 'finland' } },
];

/**
 * Returns a fallback country for the given career URL if the company is known to operate
 * exclusively in that country. Returns null if no fallback is configured.
 */
export function getCompanyCountryFallback(careerUrl: string): CountryInfo | null {
  const lower = careerUrl.toLowerCase();
  for (const entry of COMPANY_COUNTRY_FALLBACKS) {
    if (lower.includes(entry.urlSubstring)) return entry.country;
  }
  return null;
}

// Location strings that should be skipped (not a country)
const SKIP_LOCATION_PATTERNS = [
  /^remote$/i,
  /^worldwide$/i,
  /^global$/i,
  /^anywhere$/i,
  /^work from home$/i,
  /^wfh$/i,
  /^home office$/i,
  /^europe$/i,
  /^emea$/i,
  /^apac$/i,
  /^latam$/i,
  /^americas$/i,
  /^multiple$/i,
  /^various$/i,
  /^n\/a$/i,
];

function normalizeKey(s: string): string {
  return s.toLowerCase().trim().replace(/\s+/g, ' ');
}

/** Returns true if the string is a known country name or abbreviation (COUNTRY_MAP only, not cities). */
export function getCityNames(): string[] {
  return Object.keys(CITY_MAP);
}

export function isCountryKey(s: string): boolean {
  return normalizeKey(s) in COUNTRY_MAP;
}

/**
 * Looks up a city by checking whether a known CITY_MAP key is a leading word-boundary
 * prefix of the segment. Handles location suffixes like "riga central" → "riga" or
 * "tartu kontor" → "tartu" without requiring every variant to be listed explicitly.
 */
function lookupCityByPrefix(key: string): CountryInfo | undefined {
  for (const [cityKey, info] of Object.entries(CITY_MAP)) {
    if (key.startsWith(cityKey + ' ')) return info;
  }
  return undefined;
}

// Strips work-mode prefixes like "Hybrid - ", "Remote - ", "On-site - " from location segments.
const LOCATION_PREFIX_RE = /^(hybrid|remote|on-?site|in-?office)\s*[-–]\s*/i;

// Strips work-mode suffixes like "(Remote)", "(Hybrid)" appended after a location.
const LOCATION_SUFFIX_RE = /\s*\((remote|hybrid|on-?site|in-?office)\)\s*$/i;

/**
 * Extract a work model from a raw location string by looking for prefixes like
 * "Hybrid - ", "Remote - ", "On-site - ".
 * Returns 'remote', 'hybrid', or 'on-site' when all semicolon-separated segments
 * share the same prefix; returns null when there is no prefix, or segments disagree.
 */
export function extractWorkModelFromLocation(location: string): 'remote' | 'hybrid' | 'on-site' | null {
  if (!location?.trim()) return null;
  const parts = location.split(';').map((s) => s.trim()).filter(Boolean);
  const models = new Set<string>();
  for (const part of parts) {
    const match = part.match(LOCATION_PREFIX_RE);
    if (match) {
      const raw = match[1].toLowerCase().replace(/-/g, '');
      if (raw === 'remote') models.add('remote');
      else if (raw === 'hybrid') models.add('hybrid');
      else if (raw === 'onsite' || raw === 'inoffice') models.add('on-site');
    }
  }
  if (models.size === 1) return [...models][0] as 'remote' | 'hybrid' | 'on-site';
  return null;
}

/**
 * From a raw location string (e.g. "Hybrid - Helsinki, Uusimaa; Hybrid - Tallinn, Estonia"),
 * extract only the city names that belong to the given ISO alpha-2 country code.
 * Country names and cities from other countries are discarded.
 * Returns an empty array when no matching cities are found.
 */
export function extractCitiesForCountry(location: string, countryCode: string): string[] {
  if (!location?.trim()) return [];
  const parts = location.split(';').map((s) => s.trim()).filter(Boolean);
  const segments = parts.flatMap((part) => {
    const stripped = part.replace(LOCATION_PREFIX_RE, '').replace(LOCATION_SUFFIX_RE, '');
    return stripped.split(',').map((s) => s.trim()).filter(Boolean);
  });
  const results: string[] = [];
  const seen = new Set<string>();
  for (const segment of segments) {
    const key = normalizeKey(segment);
    const info = CITY_MAP[key] ?? lookupCityByPrefix(key);
    if (info && info.code === countryCode) {
      if (!seen.has(key)) {
        seen.add(key);
        results.push(segment);
      }
    }
  }
  return results;
}

export function lookupCountryFromLocation(location: string): CountryInfo[] {
  if (!location || !location.trim()) return [];

  // Check skip patterns against full location
  for (const pattern of SKIP_LOCATION_PATTERNS) {
    if (pattern.test(location.trim())) return [];
  }

  // Split by semicolon first (Greenhouse: "Hybrid - Helsinki, Uusimaa; Hybrid - Oulu, North Ostrobothnia")
  // then by comma within each part. Strip work-mode prefixes before lookup.
  // Also extract text inside parentheses as extra candidate segments — handles
  // Workday venue-style locations like "KQB (Amsterdam - Herengracht 578-58)".
  // Additionally split on " - " (spaced dash) to handle "Germany - Home Based" style strings.
  const parts = location.split(';').map((s) => s.trim()).filter(Boolean);
  const segments = parts.flatMap((part) => {
    const stripped = part.replace(LOCATION_PREFIX_RE, '').replace(LOCATION_SUFFIX_RE, '');
    const base = stripped.split(',').map((s) => s.trim()).filter(Boolean);
    const parenMatch = stripped.match(/\(([^)]+)\)/);
    if (parenMatch) {
      const inner = parenMatch[1].split(/\s*[-–]\s*|,/).map((s) => s.trim()).filter(Boolean);
      base.push(...inner);
    }
    // Split on spaced dashes (" - " / " – ") to extract sub-parts like "Germany" from
    // "Germany - Home Based" — but only add them as extra candidates, not replace the original.
    if (/\s[-–]\s/.test(stripped)) {
      const dashParts = stripped.split(/\s[-–]\s/).map((s) => s.trim()).filter(Boolean);
      base.push(...dashParts);
    }
    return base;
  });

  // Collect all unique countries found in any segment — check country map first, then city map,
  // then city prefix match (e.g. "riga central" → "riga", "tartu kontor" → "tartu").
  const seen = new Set<string>();
  const results: CountryInfo[] = [];
  for (const segment of segments) {
    const key = normalizeKey(segment);
    const info = COUNTRY_MAP[key] ?? CITY_MAP[key] ?? lookupCityByPrefix(key);
    if (info && !seen.has(info.code)) {
      seen.add(info.code);
      results.push(info);
    }
  }
  if (results.length > 0) return results;

  // Try full string as a single key (country map, then city map)
  const fullKey = normalizeKey(location);
  const fullMatch = COUNTRY_MAP[fullKey] ?? CITY_MAP[fullKey];
  if (fullMatch) return [fullMatch];

  // Try to extract a trailing 2-letter ISO country code, e.g. "Home office DK" → "DK" → Denmark.
  // \b ensures the code is a standalone word, preventing e.g. "bridge" matching "ge".
  const trailingCode = fullKey.match(/\b([a-z]{2})$/);
  if (trailingCode) {
    const codeInfo = COUNTRY_MAP[trailingCode[1]];
    if (codeInfo) return [codeInfo];
  }

  // Try a leading ISO country code — handles two Workday location formats:
  //   "FI - Helsinki" (ISO prefix with dash, used by e.g. Maersk multi-location jobs)
  //   "NLGWV03 - The Hague - De Kroon" (venue code where the first 2 chars are the ISO code)
  // The venue-code branch requires at least one digit ([a-z]*[0-9][a-z0-9]*) so that plain
  // city names starting with a 2-letter country code (e.g. "Noisy Le Sec" → "no…" = Norway)
  // are not misidentified. Real venue codes always contain digits; city names never do.
  const leadingCode = fullKey.match(/^([a-z]{2})(?:\s*-|[a-z]*[0-9][a-z0-9]*)/);
  if (leadingCode) {
    const codeInfo = COUNTRY_MAP[leadingCode[1]];
    if (codeInfo) return [codeInfo];
  }

  // Try a 3-letter leading ISO code followed by a dash, e.g. "ESP - Madrid" → 'esp' → Spain.
  const leadingCode3 = fullKey.match(/^([a-z]{3})\s*-/);
  if (leadingCode3) {
    const codeInfo = COUNTRY_MAP[leadingCode3[1]];
    if (codeInfo) return [codeInfo];
  }

  return [];
}
